
== Conclusion 
This Dark Ages section focused a great deal on efficiency. In particular, it identified that a very limited menu of ready-to-serve dishes was more efficient in terms of preparation and distribution than a menu with wide array of prepared-to-order items.  It also noted that this design is capable of processing large quantities of a given ingredient, and that this makes it possible to purchase directly from the farmer rather than a distributor.  

These are key insights because the savings reaped from these practices allows more resources to be invested in  areas that have become chronically deprived.  For example, it may be true that processed ingredients are quicker and easier to prepare than whole foods. However, if whole foods were attainable at a fraction of the current cost, then this could offset the extra labor required for preparation.  Similarly, regenerative agriculture practices may require more labor than conventional agriculture, however, if the produce can be obtained directly from the farmer, then the extra cost of labor is offset by the savings of avoiding a distributor.  In essence, efficiencies gained in one area are used to pave the way for others.  More specifically, RF looks for more efficient business processes at the micro-economic level and then reinvests the savings in more ethical and sustainable (but albeit less profitable) practices at the societal level. 

