== RF principles in institutions

The principles and efficiency espoused by RF do not find purchase in the static menu largely because the static menu offers such a variety of items.  Within a cafeteria setting, however, there is a much greater possibility of people eating the same meal.  Cafeterias have an added advantage in that they usually have limited hours scheduled around the meal times of the institution.  A large group of people eating the same food within a relatively narrow window of time is a perfect environment for RF principles to thrive.  Yet, in practice, RF principles are not observed nearly as much as one might expect.

The first thing to note is that the potential benefits of RF principles have not escaped institutions.  Both in schools and hospitals there have been attempts to source ingredients directly from farmers.  In some cases successful partnerships were made and farm-direct ingredients were incorporated.  Nevertheless, the trend did not become wide-spread and the few partnerships are established always face the same tenuous future.

The reason that institutions struggle with RF principles is simple and humbling: they have nothing to gain from them.  By definition, these institutions are organized around goals specific to their field.  For example, schools are established for the purpose of learning and hospitals to provide medical care.  Even if their cafeterias managed to reach the peak of culinary excellence it is uncertain if that would yield a single extra dollar.  On the other hand, the risks and challenges of pursuing farm-direct produce are enormous.  A single day of empty plates due to botched planning would spell doom for these institutes.  Effectively, serving food at the institute is a reluctant concession.  Were there not a need to long school days and inpatient hospital stays, they would certainly forego the entire food offering.  Given that they must offer food, they seek food that poses the least risk and the most predictability lest the food service threaten to distract from their core competency.

By constrast, RF advocates for for-profit food service to be the ideal environment for its principles.  It recognizes that new approaches are inherently risky and that if an entity is not poised to profit from the potential benefits then there is no incentive to take the risks.  Whereas the number of meals served in a school is limited to the students and staff, a successful food service establishment can draw customers from far and wide.  Equally important is the outcome of unsuccessful attempts.  A school that fails to meet the food service duties it has been charged with would be liable to the parents and community.  A for-profit establishment would have no such liability.  If errors in the kitchen meant no food, it could mean business disaster, but no matter how disastrous, the problem would be contained within that establishment.  Would-be customers may be disappointed or inconvenienced but the establishment would not be liable for those negative feelings.

One final point to underscore is that the risks and incentives must be properly captured by the market in order to be effective.  For example, a school could be said to have incentives to provide healthier food because the students will learn better with it.  Likewise, patients in a hospital may be healthier if given healthier food. Nevertheless, it is hard to define and quantify these benefits therefore they get factored out of the equation.

The lesson from this section is that RF principles can only take hold in the proper environment.  Institutions may offer conditions that superficially resemble what one would expect from RF, however fundamentally they are not equipped to balance the risks and incentives.  Therefore, even the best of intentions cannot provide an adequate foundation for true growth in RF.
