= Rehabilitating our kitchens

Years of static menu, prepared-to-order food service have ravaged our kitchens. The relentless pressure to deliver freshly prepared food as fast as possible has created a truly dysfunctional culture of stress and strain.

That so many of us dine out regularly and yet take this fact for granted is a testament to the insidiousness of the culture that has taken hold. 

Indeed, it is at the higher-end, gourmet restaurants that this dysfunction is most pronounced. Consider the recent peer-reviewed study entitled _Alcohol and other drug use in Michelin-starred kitchen brigades_. The highlights from the very first page of article should be enough to give everyone pause:

* Alcohol and other drug (AOD) use appear to be part of the everyday life in Michelin-starred kitchen brigades in Britain and Ireland.

* AOD were found to be used as a means of self-medication and as a coping strategy for most chefs regardless their ranking.

* Alcohol is used to unwind after work and cope with the harsh working environment.

* Drugs and other substances are mainly used to maintain or improve performance. 

That these findings come from the most prestigious establishments in the world implies that this situation arises not for lack of money or expertise.  It cannot be dismissed as a symptom of the low socio-economic standing of the employees, much less the diners.  It is quite simply a dysfunctional culture of its own creation.  

The idea that this arose from within industry itself is an important realization because it underscores the fact that this dysfunctional system is often rewarded and is seen as a necessary sacrifice, the price of working at the world's finest kitchens.

- Quote Anthony Bourdain


== Monotony of the static menu

The first piece of the problem is the static menu itself.  Preparing the same dishes day-in and day-out is monotonous. This dulls creativity. In an RF establishment, the menu is constantly adaptable, so ideas can be incorporated into the dish the next time it is prepared. This encourages employees to think critically about the dishes they are preparing.

The dynamic nature of the RF establishment rewards employees with greater culinary knowledge. When preparing a new dish, these employees conceptually examine the task rather than approaching it in rote fashion.  They are able to understand the significance of the ingredients in the recipe. Perhaps they are even able to propose a replacement ingredient in the case that one is in short supply.  The establishment stands to benefit greatly from such employees, and in turn, has the incentive to reward and cultivate deeper culinary knowledge in its employees.

=== Demand volatility

The second issue is prepared-to-order food.  This has two pernicious effects.  First, because the establishment has no control on when customers walk in the door, it is vulnerable to spikes of business.  In fact, one might even say that spikes are the norm, as most people eat at similar times of the day. 

No one likes to wait, least of all a hungry person for their food. Management understands this and places an emphasis on timely service in order to keep their customers happy.  Effectively, management uses the work force as a buffer for this volatility; they absorb the spike in demand in the form of stress.  For this reason, spikes in customers translate into spikes of stress for the kitchen. 

=== Labor volatility

Second, prepared to order food leaves kitchens more vulnerable to labor volatility. If a staff member calls in sick, establishments have little means of closing that gap. This translates into additional stress for the remaining kitchen staff as they try to uphold customer expectations of timely service. 

For an RF establishment that does the bulk of preparation in advance, there is likely to be more time to fill the gap before it impacts the customer.  Moreover, the RF establishment may be able to cover the gap with additional labor on a different shift, whereas the static menu must find someone to cover the exact shift of the sick employee.  In essence, the RF establishment can average out labor shortfalls with additional labor at a different time.  (Employees may be more likely to be pressured to work when sick due to static menu rigidity.)

=== Blast radius

A final, more subtle factor in the prepared-to-order business model is that because each dish is prepared individually, if an employee makes a mistake, only a single dish is affected. What is more, the customer can catch that mistake almost immediately. These dynamics enable the static menu establishment to maintain chronically stressful labor conditions because the impact of mistakes is relatively contained.

For an RF establishment, because many dishes are prepared in bulk in advance, a mistake in preparation will likely affect many more servings and has the potential to go unnoticed for longer.  Ironically, the fact that mistakes are costlier for RF is ultimately a harmonizing factor in labor practices.  Because mistakes are more frequent in stressful situations, it means that the worker and the establishments are aligned in their incentives: both want to avoid stressful working conditions. Therefore, business will be more strongly incentivized to maintain low-stress working conditions in order to avoid these more costly bulk mistakes.

== Gratuity culture

Many restaurants with higher-quality dishes tend to pay servers with gratuity.  This has the advantage that it offloads some of the business risk associated with sales volatility onto the staff because the servers receive a significant portion of their compensation from the customers. Again, we see the theme of the workforce acting as buffer for the businesses' sales volatility.

This arrangement is already dubious but the worst thing is that gratuity is completely left up to the customer. This opens the door to all sorts of unjust outcomes in which the server is docked on their gratuity based on a customers' dissatisfaction with the kitchen.  In turn, tensions between the kitchen and the servers arise. Effectively, the customer is able to use the gratuity as a proxy attack against the kitchen (or anything else about the establishment).  This manifests in highly nuanced interactions between the server and the customer.  For example, if the customer requests a modification to a dish and it is not done, in their apology the server may note that the kitchen forgot to do it. This "pointing the finger" is the server defensively signaling to the customer that they put in the request and it was the kitchen's fault. Therefore, the customer should not use this as a reason to dock their gratuity.  This drama does not help in serving food to customers.  It is baggage that the industry clings to.

If things were not bad enough, gratuity culture also dictates that each table gets one dedicated server.  Making requests to any other staff member is frowned upon.  This is because that person won't get compensated with gratuity for helping with your request.  Accordingly, one can expect that for any given request, employees who are otherwise perfectly capable of helping will likely walk right past while one vigilantly waits to catch the eye of their server (who hopefully hasn't just gone on a break). Notice how this fragile model is stressed even in the time it takes the server to use the bathroom.

In some cases, the entire aspect of service is a pretense.  The arrangement is more akin to a quick-service restaurant, in the sense that they do not plan on providing service for anything except the initial request. The point the only clear expectation of gratuity seems to be that someone takes your order and brings your food to your table.  Whether that person intends to be available for any other requests is entirely unclear, yet the expectation of gratuity of at least 15% is clear.  Simply put, gratuity if it ever held any merit, has now simply been reduced to a business strategy, not an actual quantifiable service.

The arguments in favor of gratuity are so weak as to be nonexistent.  Virtually any argument can be dismissed by simply questioning why, if gratuity is so useful, doesn't it make up the bulk of one's income in any other industry. It is truly a practice as peculiar as it is dysfunctional and it only serves to exacerbate the many other ills facing the industry.

=== Back-of-house gratuity "Can't teach old dog new tricks"

A new trend in food service is to include an extra service fee for "Back-of-house". Given the immense shortcomings of gratuity, this new fee represents an awkward nod to that broken system.

There are several curious things about this. First is the way it is presented.  While gratuity is a very familiar concept that most all customers can intuitively recognize, there is no outward indication of the coming fee.  That is, except for the fine print at the bottom of the menu.

There is a reason that fine print has a negative connotation. It comes from the way some businesses present pertinent information - information about additional costs - in a way that the customer does not take note of.  So-called "hidden costs".  This perfectly captures the back of house fee that is about as prominently displayed as a warning not to eat raw shellfish, which is to say, it is displayed just enough to cover legal liability.

It is all too easy to overlook the fine print, not just because it is designed to be overlooked, but also because something so irrational cannot possibly be expected by the customer.  Since it is a percentage fee identical to sales tax, it means the restaurant could have just as easily raised their prices by an equal percentage.  Instead, they choose to engage in this "back-of-house" chicanery. 

The "back-of-house" fee allows these establishments to appear more price-competitive by "hiding" the additional cost from the customer. It is packaged as a "back-of-house" fee in order to imbue it with moral authority.  The customer is supposed to feel responsible for ensuring the fair pay of those preparing their food, just as the gratuity model puts servers' fair pay in the hands of the customer. (Importantly, the customer is not supposed to question why the establishment wouldn't pay an appropriate wage in the first place.  Presumably, the business is so cash-strapped that they could not even afford to pay a fair wage.  It is truly a revealing display by management.)

Finally, all of the moral posturing offers no guarantee of a more moral outcome.  In fact, theory would predict that once the back-of-house fee becomes endemic in the industry, that establishments will offer commensurately less in guaranteed wages.  This is true because if these employees were vulnerable to exploitation from low pay in the first place, then this new fee will not change that power dynamic, it will simply manifest in a new way. 

Critically, though theory predicts an equal outcome in employee wages over the long-term, the establishment still comes out ahead because it trades guaranteed wages for sales-dependent ones.  This is the same theme as noted earlier of the business using the workforce as a buffer for sales volatility.  ("You old dog, you")

- It is questionable that a customer can visit an establishment and never notice they are paying the new fee. Unless one looks carefully at the taxes and fees, it is all too easy to overlook it.
