== Meat-centric

A defining characteristic of the static menu is it's use of meat.  In particular, the static menu makes meat the showcase of its menu.  Often this comes in the form of a filet of meat.

There are several reasons that the static menu does this.  The first is that meat is not seasonal nor as perishable as fresh produce.  This means that it can be obtained year-round for a relatively consistent price.  This fits well with the static menu because it serves the same dishes year-round.

A more subtle factor driving meat consumption is the inefficiency of the static menu.  Because it cannot serve a large volume of customers, it must make a relatively larger profit from each customer.  Meat is a more expensive ingredient that pushes up the price of a dish.  In turn, higher prices lend to higher profit margins because the increased profit represents a smaller proportion of the overall price.

Finally, meat has a cooking time that is in keeping with the time customers are willing to wait for their food.  This means that meat-centric dishes can be prepared-to-order, as is characteristic of the static menu.

RF is revolutionary in its ability to buck the trend of meat dominance in food service.  The environmental benefits of reduced meat consumption are worthwhile on their own, but RF is equally motivated by frugality.  That produce is a more economical ingredient than meat should be an obvious fact to anyone.  Estimates suggest that it requires X as many resources to produce an equivalent amount of calories from meat than produce.  This is easy to understand when you consider that you must feed the livestock produce to eventually get the desired meat.

Despite the fact that calories are more efficiently generated by produce than livestock, the relative prices of the two do not always reflect this efficiency due to the deep dysfunction and inefficiency of the food supply chain.  Intermediaries are so inefficient, greedily exploiting power dynamics and seeking to supply the same ingredients that the consumer may often find that fresh produce is relatively expensive.  RF deftly cuts through this gross distortion of the markets by sourcing ingredients directly from the farmer or by choosing only ingredients that are plentiful in the present moment.  This means that RF can obtain its produce significantly cheaper than the static menu, cheap enough that de-emphasizing meat in the menu becomes a compelling business consideration.

Secondly, RF is efficient in serving and preparation.  It seeks profit by offering value to the consumer.  In effect, it seeks a small profit from each dish but to serve a high-volume of customers.  This is the opposite mindset that tries to squeeze as much from each customer as it can.  In this sense, RF has nothing to gain from higher price points in the same way as the static menu.

Lastly, because RF prepares food in advance, the relatively longer preparation times of fresh produce are less significant. 

