== Food waste 

Food waste is a major issue in America.

 It is estimated that up to 40% of food is wasted <<wasted-nrdc>>.

The consequences come not just in the form of higher food prices but also environmental strain from the fertilizers and fossil fuels used in producing the unused goods.

In 2012, the Natural Resources Defense Council published __Wasted__, a landmark document chronicling the food waste in the US. It systematically examined food waste in every step of the supply chain and the relative rates of waste of different food types. 

 found which foods were being

It found that up to 40% of food is wasted. 

Along with their exhaustive food waste analysis, they provide a veritable laundry-list of food waste remedies.

 From telling your friends about the importance of food waste t

From using a smaller dinner plate to standardizing food waste metrics in the federal government, opportunities to reduce food waste abound.

While it provides an extensive list of remedies, it does not compare the relative merits of these remedies. In particular, several principles of RF are touched upon individually but their combined potential within the context of RF warrants further discussion.

Following the same pattern of supply chain dissection as __Wasted__, RF techniques to reduce food waste will be presented and contrasted with other remedies.

=== Consumer

"Wasted"'s analysis showed that the consumer represents the largest source of waste in the food system. It also notes that "[b]ecause it has undergone more transport, storage, and often cooking, throwing food away at the consumer level has a larger resource footprint than at any other point of the food chain."

Given the high impact of waste in this area, it is an important focus for any food waste reduction effort.  However, this does not mean that improvements in this area are readily achievable, and more importantly, it does not mean that the consumer is necessarily an effective agent of such change.

The second point is critical because researchers frequently focus on influencing the shopping and eating habits of the consumer. By educating them about the environmental impact of food waste or by sharing techniques to reduce waste, they hope to encourage behaviors that lead to less food waste.

A major problem with these approaches is that they place too big of a burden on the consumer. 
 In reality, the cost of adopting many of the consumer-focused reduction efforts is considerable. 

For example, the report cites "[l]ack of meal planning and shopping lists" as a driver in food waster. However, such planning can be complex and time-consuming.  Selecting recipes, tallying the required ingredients and checking your current stock of these ingredients must all be done before going to the store.  Do you have half a bottle of sauce that is on the brink of spoilage? Then you must tailor your recipe selection to include that item.  Ultimately, reducing waste by this route translates to careful inventory management and requires knowing (at least roughly) how much you have of each ingredient and what its expiration is.  Last but not least, all of this planning must occur prior to going shopping and must remain unwavering during the shopping.  Notice something on sale?  Too bad.  Deviation from your shopping list is a risk factor for food waste.

Intertwined with the consumer burden topic is the trend towards smaller household sizes that was noted earlier.  Recipe planning and inventory management take virtually the same time regardless of how many servings are being made.  Therefore, consumers are being encouraged to adopt practices that are becoming increasingly less valuable as household size continues to shrink.

Finally, a conceptual problem with influencing consumer behavior is that consumers are already have a direct economic consequence from food waste: the money lost. Economic consequences are generally accepted as some of the most effective incentives. Therefore, waste clearly has very strong drivers and public messaging is not likely to budge the entrenched behavior. Moreover, the public messaging is in relation to an externality, whereas the lost money from wasted food is an internality for the consumer.

==== The RF approach

From the viewpoint of RF, consumer food waste is simply a side-effect of a much bigger issue. The real question is not how the consumer can optimize their food preparation but why the consumer is doing so much food preparation in the first place.  The reason is that food service has failed to meet society's needs to such a dramatic extent that people have given up on the expertise, economies of scale, etc that food service can offer and instead take on the task themselves. This behavior is contrary to every expectation of the capitalist model.

On the other hand, if healthy, affordable and convenient food were readily available, the consumer would take on less food preparation thereby generating less waste.  The key is that the consumer doesn't need to plan several days ahead when eating from food service.  On the other hand, preparing one's own food often involves planning meals for several days and that leads to waste when plans change or prove incorrect.  This is especially true because the threat of having too little food trumps the consequences of wasting food, thus people err on the side of waste.  RF means less waste-prone speculative decisions for the consumer.

One could argue that this only shifts the burden of planning to food service.  This is true, but food service is much more capable of planning than the consumer and also more adaptable.  For one, if food is going to expire in your own fridge, then only you can prevent that. But for food service, there is an entire world of people to potentially sell that food to.

In conclusion, RF advocates for people getting their food from food service as close as possible to the time it is eaten. This is the ultimate in efficiency and waste reduction.  In contrast, buying all of one's food for the week at a supermarket to then prepare it at home is the ultimate burden and opportunity for waste. 

- the consumer cannot prepare food as effectively as food service, and poor inventory management leading to food waste is simply one example of that.

- It is not simply coincidence that the report proposes measures that place a heavy burdey on the consumer.  This is because the consumer is seen as a malleable entity in the food system, whereas the industry is seen as rigid and difficult to change.

=== Food speculation

 On the surface, it would seem that the consumer is perhaps the only one capable of reducing waste at the consumer level. After all, if it the same consumer that throws away the food that they purchased only days earlier, then who else is to intervene.

 While it is certainly true that the consumer plays a principal role in consumer-level food waste, they are not the only party capable of influencing it.  In particular, RF has great potential to reduce waste.  However, before discussing the potential of RF, the potential of the existing remedies must be discussed.

 I would argue that the greatest challenge of the existing remedies is they place too great of a burden on the consumer. This point is noted in Wasted where they note that "time constraints and inconvenience can exacerbate the problem."  

 However, because it does  examining the potential of the various remedies, the significance of these time constraints may not be apparent.

=== Buy less

A second example of a consumer-focused food waste remedy is buying items in smaller quantities. 

The idea is that if the consumer wastes a portion of an item then they would have been better off buying less of that item. Proponents of this solution further note that producers often incentivize purchases of larger quantities, which contributes to over-purchasing.  

This particular remedy offers tremendous insight into the challenges of the issue.  For on the surface, it seems nonsensical. Producers are simply offering a bulk discount and consumers are stocking up for future meals. Volume discounts are commonplace in most industries, so why discourage them in relation to food?

The reason is that policy-makers believe that consumers makes poor decisions in relation to bulk food purchases, that they are lured by the bulk discount into purchasing more than they can really use.  This may in fact be true. But the more important point is that this is not about bulk pricing.  It is about consumer psychology. The consumer over-estimates their commitment, therefore they are being advised to make smaller commitments.  What a slippery slope to navigate! Advocating that consumers forego bulk discounts is implicitly insulting to the consumer.

==== Bulk food

__Wasted__ cites bulk food grocers as a potential remedy because consumers can purchase exactly what they need.  Theoretically, there are undeniable benefits to this, but in practice its application proves disappointingly limited.  There are simply not enough food items that are available in this format.  There is also the extra burden of having to weigh each item.  In general, if the same quantity of goods were available in a packaged format versus a bulk format, the former would offer a more streamlined shopping experience (e.g. less weighing and manual data entry of item codes), better protection for the goods while in transit and better communication of information regarding the ingredient (e.g. origin, nutrition).

Finally, it is worth while to note that the greatest proportion of food waste comes from produce, which is a type of product in which consumers are often able to select items individually.  This demonstrates that perfectly choosing quantities is far from a silver-bullet in terms of waste reduction.

 The logic behind this remedy is appealing but ultimately proves too reductive. 

Even the framing of the matter with the term "inconvenience" seems to minimize the true cost of what is being asked of the consumer. 



Within this list of potential remedies, several RF principles are touched upon.

 provides a near-exhaustive examination of where food is wasted, the consequences of that waste and the remedies that are available.

The consumer wastes much more than retail. Does that indicate there is a lot of room for improvement there? Maybe not. Means the consumer is overwhelmed.

RF could create food scraps that are not heavily processed, containing preservatives, etc.  More useful in a circular economy.

Farming is too speculative. Crop prices change, etc.  A CSA model removes a great deal of the speculation.  Also, food service serves as a direct conduit of consumer preference. The intermediaries buy speculatively based on price.  Food service buys to use it directly. Better gauge of usage than commodities markets.

=== Consumer bias

A great benefit of seeking food waste reductions via food service is that the consumer does not reliably estimate their food waste.  They have no systematic way of tracking the multitude of items in their kitchen.
