= Food waste in production

"Wasted" found huge losses in the production process of food.  This discussion will focus exclusively on produce waste because it represents the biggest area of potential improvement under RF.

The issues driving produce waste are directly linked to the major role of distributors and intermediaries in the food system.  To put it another way, food is wasted in production not because the food has no value, but because it has no value for intermediaries.  

The most prominent example of this is when fields go unharvested due to market prices.  "When prices are low, growers may leave entire fields unharvested if those prices will not cover the costs of bringing the product to market."  Because intermediaries are not the actual consumers or processors of food, their very existence increases the costs of bringing product to market.

The effect of intermediaries is also felt in more subtle ways such as contract requirements. This is when an intermediary requires a farmer to produce a certain quantity but resesrves the right to not purchase that same quantity. 

Finally, the farmers themselves sometimes "speculate on the possibility of higher prices", which results in waste when those speculations prove incorrect.
