= Food service investing in the farmer

 The importance of this new connection between food-service and the farmer cannot be overstated.  Indeed, nearly everything in the book hinges on it.  The closer the relationship that can be forged between these two parties, the more benefits there are to be reaped.

The regenerative agriculture section noted how RA farms often struggle bringing their product to market. RF offers a new approach that eliminates the problem entirely.  By purchasing shares in advance, the farmer does not have to worry about bringing their product to market.  Instead RF brings the market to the farmer, which is to say the RF invests in in the product before the seeds are sown. Rather than waiting until the harvest in reaped.

== More diverse crops

Markets are fickle. RA can grow crops in a sustainable way, but is still at the mercy of downstream markets.  The homogeneity of food service means that so-called "specialty" ingredients will be used minimally.  In essence, the demand for these items is weak. 

Investing in the farm is the key to overcoming the homogenizing force of the broader market.  Because the sale of the product is ensured, the demand in the broader market is a moot question.


== Crop insurance

Is crop insurance causing single-crop production and other risk taking behavior?  Effectively creating a moral hazard dysfunctionality.

== Conclusion

 The importance of this new connection between food-service and the farmer cannot be overstated.  Indeed, nearly everything in the book hinges on it.  The closer the relationship that can be forged between these two parties, the more benefits there are to be reaped.



