= Deeper farmer relationships 

It has been mentioned that RF seeks to source ingredients directly from farmers as a cost-cutting strategy. Efficiency gains such as these are appealing because they are readily apparent and can be easily calculated on a balance sheet.  However, other less-tangible but significant benefits also arise from closer farmer relationships. For this reason, building relationships between farmers and food service is paramount in RF.  

== Diverse purchases

The first intangible benefit is that RF is flexible and adaptable to ingredient availability.  Whereas the static menu requires specific ingredients in exact proportions, RF is flexible.  To put it another way, the static menu starts from its own menu requirements and seeks farmers that can accommodate them.  RF starts with the farmer and tries to adapt the menu to accommodate the ingredients available from the farmer. This greatly increases the possibility that a farmer can supply their ingredients.  Moreover, it increases the possibility of sourcing multiple ingredients from the same farmer.  In this way RF facilitates deeper relationship with farmers.

Finally, this mindset is important because it gives the farmer the latitude to focus on improvements to soil health rather than catering to the whims of the static menu.

== Ugly vegetables

Along the same lines of RF being more accommodating of ingredient availability, it is also more accommodating in terms of the produce grades.  Distributors are notoriously inflexible in terms of produce grades, leading to enormous waste of items that are perfectly edible but do not have the desired size or shape.  This obsession with grades is a consequence of the fact that they are speculators seeking to sell to the retail sector.  Grading produce is a form of standardization that simplifies their business model.  If they can confidently know that all the produce in a shipment is of a similar size and shape, then it is easier to sell that produce because it can be compared to others based solely on weight.  In this way, grading produce facilitates the ability to trade it as a commodity.

 Some in the retail sector may have a genuine need for produce that conforms to a desired grade and on account of this possibility, distributors find it easiest to rigidly adhere to grading.  

This is perfectly understandable from the standpoint of the intermediaries but has little benefit to the retail sector.  Some would argue that the retail sector benefits from lower prices by way of the arbitrage that occurs with a standardized commodity.  However, this is really only true for those limited retail buyers that genuinely require produce of a specific grade. If one were open to produce of a variety of grades, then the cost of the intermediaries would surely outweigh and benefit of them. 

Another reason that the static menu is more averse to irregular produce is because it seeks to serve the same identical dish every day.  Not just that, the static menu is conformist. It is common to see many establishments serving highly similar dishes.  In this context, establishments compete to offer the most quintessential take on a dish and irregularity is seen as a shortcoming. (For example, it is desirable for the slice of tomato served on a burger to be a similar diameter as the bun.) Vanity trumps practicality for the static menu.

Ultimately, it is the deep reliance of distributors that precludes any true embrace of diversity in ingredients.  However, the static menu itself is content with the situation due to its deep-seated vanity.

Moreover, they could not accommodate the irregular produce on an occasional basis. This shows the depth of the pathology of the static menu.  If it could put aside its vanity and agree to use the irregular produce, it would then ask to be given the same irregularities in the same proportions each day.  It cannot handle variability. 

 Technically, this is less of a distinction of the static menu and more of a side-effect of it.  The static menu m  In the same veinFarmer-food-service relationships are better able to use produce of multiple grades.

 They seek consistency of price of ingredients in order to offer consistent prices.  

== Agricultural practices

A crowning distinction between the current food system and RF is in agricultural practices.  The static menu and its cadre of intermediaries seek uniformity and consistency.  If a farmer were to tout their progressive agricultural practices during a business discussion, they would be dismissive.  It is not so much that they doubt the farmer.  Rather, they are too crude and reductive (and arrogant) to know what to do with it.  They operate based on gradation of empirically observable traits. 

If, for example, a farmer adopted drip-line irrigation in order to improve water conservation, they could not readily pass those costs downstream to the consumer.  The intermediaries would be frustrated that the produce is distinguished by water conservation as well as the usual grading system, leaving their inventory fragmented.  In turn, the static menu establishments would be frustrated in how to account for the higher price of these ingredients.  They could not effectively communicate the positive aspects of this to the consumer. 

Finally, the current food system struggles mightily in tracking the origins of produce.  This is amply demonstrated in food recall outbreaks in which the industry must go to great lengths to trace the origins.  Only in these isolated situations that are matters of life and death can the supply chain be truly known.  Worse yet, false claims of origin are rampant.  Therefore, distinctions like reduced water usage, which are not measurable in the final product are next to impossible to incorporate into the business model.  And even if intermediaries did genuinely wish to account for such distinctions, the public would quite rightly doubt the authenticity of the claims and be reluctant to pay extra.  Long, complex supply chains suffer from a severe lack of trust.

Fragmentation of the inventory relates to food recall outbreaks.

ASIDE - Organic is an example of gradation but is abused and is susceptible to many of same issues as conventional
