== Farm labor

- Problem with this section...Better to argue that we need higher skilled agricultural work that favors long-term employment over seasonal work. Permaculture and diversified tasks could offer that.  
 - RF embraces the dynamic nature of agriculture and seeks to adapt to it. This means a constantly evolving set of tasks and priorities. In turn, higher skill sets are required.  Careful attention and adaptability are required. Knowledge and experience carry greater worth.

A tangential topic to farm profits is farm labor.  It is well-known that the current agricultural industry in dependent on labor from undocumented immigrants.

This is a complex issue intersecting things like immigration policy, power exploitation and farm economics.  RF cannot address all of these factors but it could significantly affect farm economics. Simply put, if the farmers themselves are facing financial struggles, it will be that much harder for them to pay higher wages and provide better working conditions.

This is not meant to excuse the situation. To the contrary, this removes a major complicating factor in achieving meaningful improvements in these issues.  To the extent that farmers face financial hardships, there will be incentive to excuse the issues because of fear of bankrupting the very people who secure the nations food supply.  With farmers on the ropes, we are hamstrung in addressing the issues that occur on those farms. Increasing farm profits will bring the other issues into clearer focus.

In _Perilous Bounty_ the author recounts an interview with a farmer in then Central Valley.  The farmer tells how his business is uncertain due to increasing labor costs.

Argument for illegal immigrants is that cannot pay a good wage and simultaneously meet the demands of the American populace. In fact, unlike all other industries, the federal law mandating additional pay for more than 40 hours per week does not apply to agriculture.  However, this has been changed by the state legislature effective 2022 and in 2023 the state's minimum wage increases.

 If the increased cost of labor translates to higher costs of fruits and vegetables then that makes it harder to provide healthy food.

