== Food waste 

Food waste is a major issue in America.

 It is estimated that up to 40% of food is wasted <<wasted-nrdc>>.

The consequences come not just in the form of higher food prices but also environmental strain from the fertilizers and fossil fuels used in producing the unused goods.

In 2012, the Natural Resources Defense Council published __Wasted__, a landmark document chronicling the food waste in the US. It systematically examined food waste in every step of the supply chain and the relative rates of waste of different food types. 

 found which foods were being

It found that up to 40% of food is wasted. 

Along with their exhaustive food waste analysis, they provide a veritable laundry-list of food waste remedies.

 From telling your friends about the importance of food waste t

From using a smaller dinner plate to standardizing food waste metrics in the federal government, opportunities to reduce food waste abound.

While it provides an extensive list of remedies, it does not compare the relative merits of these remedies. In particular, several principles of RF are touched upon individually but their combined potential within the context of RF warrants further discussion.

Following the same pattern of supply chain dissection as __Wasted__, 
RF techniques to reduce food waste will be presented and contrasted with other remedies.

=== Consumer

"Wasted"'s analysis showed that the consumer represents the largest source of waste in the food system. It also notes that "[b]ecause it has undergone more transport, storage, and often cooking, throwing food away at the consumer level has a larger resource footprint than at any other point of the food chain."

Given the high impact of waste in this area, it is an important focus for any food waste reduction effort.  However, this does not mean that improvements in this area are readily achievable, and more importantly, it does not mean that the consumer is necessarily an effective agent of such change.

The second point is critical because researchers frequently focus on influencing the shopping and eating habits of the consumer. By educating them about the environmental impact of food waste or by sharing techniques to reduce waste, they hope to encourage behaviors that lead to less food waste.

A major problem with these approaches is that they place too big of a burden on the consumer. 
 In reality, the cost of adopting many of the consumer-focused reduction efforts is considerable. 

For example, the report cites "[l]ack of meal planning and shopping lists" as a driver in food waster. However, such planning can be complex and time-consuming.  Selecting recipes, tallying the required ingredients and checking your current stock of these ingredients must all be done before going to the store.  Do you have half a bottle of sauce that is on the brink of spoilage? Then you must tailor your recipe selection to include that item.  Ultimately, reducing waste by this route translates to careful inventory management and requires knowing (at least roughly) how much you have of each ingredient and what its expiration is.  Last but not least, all of this planning must occur prior to going shopping and must remain unwavering during the shopping.  Notice something on sale?  Too bad.  Deviation from your plan is a risk factor for food waste.

Intertwined with the consumer burden topic is the trend towards smaller household sizes that was noted earlier.  Recipe planning and inventory management take virtually the same time regardless of how many servings are being made.  Therefore, consumers are being encouraged to adopt practices that are becoming increasingly less valuable as household size continues to shrink.

Finally, a conceptual problem with influencing consumer behavior is that consumers are already have a direct economic consequence from food waste: the money lost. Economic consequences are generally accepted as some of the most effective incentives. Therefore, waste clearly has very strong drivers and public messaging is not likely to budge the entrenched behavior. Moreover, the public messaging is in relation to an externality, whereas the lost money from wasted food is an internality for the consumer.

 - hope to be if the consumer already ignores direct economic consequences? Public messaging is not likely to sway behavior where economic incentives have already failed. 

It is not simply coincidence that the report proposes measures that place a heavy burdey on the consumer.  This is because the consumer is seen as a malleable entity in the food system, whereas the industry is seen as rigid and difficult to change.  The field has arrived at this conclusion after failed attempts to influence industry either by way of regulation or moral suasion.  However, RF represents a paradigm shift that encompasses the entire system, not seeking to infuence just one entity in the system. It is also driven by the markets, not requiring regulation or intevention.  It affords a vast scope of possibilities that prompt a complete reassessment of the landscape.

With this new outlook in hand, a critical insight becomes apparent: that food waste at the consumer level is driven by speculation.  Because healthy, affordable and convenient food is not readily available, the consumer is forced to take on (some of) the task of food preparation themselves.  Naturally, the consumer attempts to purchase enough food for multiple meals on a single trip to the store, lest they find themself going to the supermarket each day.  Thus, they speculate on what they will eat the next few days.  When they get home, they prepare the food and likely make extra servings, speculating on how long the leftovers will keep and how fast they will eat it.  These two speculations open the door to the majority of the consumer food waste problem.

Like most speculations, the consumer speculations on food are an attempt to optimize resources. By accurately predicting what you eat for several days, you can do it with less trips to the store and less time in the kitchen. This makes sense if you feel that it the only means to healthy and affordable food.  However, there is no reason to think that. Food service is infinitely more capable than the consumer will ever be.  In any other industry, this fact is painfully obvious.  Mechanics work in a garage.  Doctors work in hospitals.  You wouldn't expect to replicate those services at home with the same efficiency (if at all).  Yet, when it comes to food service, the industry has failed to meet society's needs to such a dramatic extent that the consumer behaves contrary to every expectation of the capitalist model.

- The problem is that it is based on a false notion of scarcity. Why go to the store or cook the food at all (if you don't want to)? If it is a question of saving time and money, food service can prepare food much more efficiently than the consumer could ever dream.  RF contends that healty, affordable and convenient food need not be scarce at all.

RF advocates for people getting their food from food service as close as possible to the time it is eaten. This is the ultimate in convenience and waste reduction.  In contrast, buying all of one's food for the week at a supermarket to then prepare it at home is the ultimate burden and opportunity for waste. 

 - (Notably, the design of our cities and our shops means that a supermarket is not necessarily near one's home nor is it convenient to stop in for a single item.) This speculative shopping opens the door to virtually all of the ills of food waste.  It is all too easy to see an item on sale and to rationalize that it can be used in the coming days.  Purchases driven by cravings and bulk-savings can be similarly justified.

- To appreciate the toxic nature of this speculation it is first important to note that it serves no value to the consumer.  It is a task of resource allocation under a false sense of scarcity.  Who would choose to store a week's worth of food if they knew that healthy, affordable and convenient food was readily available? There is no benefit to hoarding food in that manner.  Not only does it risk the food going to waste, but it is simply inconvenient to have to store it in one's house. 

Thus, it can be seen that the scarcity of quality food service pushes the consumer into a game of speculation which results (quite predictably) in waste because the threat of having too little food trumps the consequences of wasting food.  

- An excellent analogy is that of gasoline.  It is perfectly possible to buy gasoline in bulk and store it at one's home to reduce the number of trips that one makes to the gas station. However, such behavior is virtually unheard of because consumers trust that they can obtain gas quickly, conveniently and at a fair price whenever they need it.  Consumers do not share the same feelings about food, however. 

- at a supermarket is is to the time)  Reducing the threat of food reduces the need to engage in such speculationas the time-starved, emotionally-inflenced, and advertising-susceptible consumer struggles to navigate their daily dietary requirements.

- conceivably And because food preparation is complex, this  and confronts the consumer with numerous considerations, This is a complex task In tu

- Finally, we should note that zero food waste is not actually even the ideal.  It is perfectly natural that people will want extra stores of food beyond even what they have plans for.  The inconvenience of running out of food is too great that people will instinctively prefer a surplus to a deficit, even if that means waste.  One could argue about what an adequate surplus ought to be, but this is a very subjective and personal matter.

=== Food speculation

A second problem with these approaches i

That is why I do not believe that the consumer is an effective agent of change, which is to say, that you cannot leave everything else the same and hope to have the consumer behave differently.

"impromptu"

to be less wasteful. On the surface, it would seem that the consumer is perhaps the only one capable of reducing waste at the consumer level. After all, if it the same consumer that throws away the food that they purchased only days earlier, then who else is to intervene.

While it is certainly true that the consumer plays a principal role in consumer-level food waste, they are not the only party capable of influencing it.  In particular, RF has great potential to reduce waste.  However, before discussing the potential of RF, the potential of the existing remedies must be discussed.

I would argue that the greatest challenge of the existing remedies is they place too great of a burden on the consumer. This point is noted in Wasted where they note that "time constraints and inconvenience can exacerbate the problem."  However, because it does  examining the potential of the various remedies, the significance of these time constraints may not be apparent.

A second example of a consumer-focused food waste remedy is buying items in smaller quantities. 

 The logic behind this remedy is appealing but ultimately proves too reductive. 

The idea is that if the consumer wastes a portion of an item then they would have been better off buying less of that item. Proponents of this solution further note that producers often incentivize purchases of larger quantities, which contributes to over-purchasing.  __Wasted__ cites bulk food grocers as a potential remedy because consumers can purchase exactly what they need.  

This particular remedy offers tremendous insight into the heart of the issue.  For on the surface, it seems nonsensical. Producers are simply offering a bulk discount and consumers are stocking up for future meals. Volume discounts are commonplace in most industries, so why discourage them in relation to food?

Policy-makers believe that the consumer makes poor decisions in relation to bulk food purchases, that they are lured by the bulk discount into purchasing more than they can really use.  This may in fact be true. But the more important point is that this is not about bulk pricing.  It is about consumer psychology. The consumer over-estimates their commitment, therefore they are being advised to make smaller commitments.

There are several challenges with this approach.  Finally, it is worth while to note that the greatest proportion of food waste comes from produce, which is a type of product in which consumers are often able to select items individually.  Therefore, perfectly choosing quantities is far from a silver-bullet in terms of waste reduction.


Even the framing of the matter with the term "inconvenience" seems to minimize the true cost of what is being asked of the consumer. 



Within this list of potential remedies, several RF principles are touched upon.

 provides a near-exhaustive examination of where food is wasted, the consequences of that waste and the remedies that are available.

The consumer wastes much more than retail. Does that indicate there is a lot of room for improvement there? Maybe not. Means the consumer is overwhelmed.

RF could create food scraps that are not heavily processed, containing preservatives, etc.  More useful in a circular economy.

Farming is too speculative. Crop prices change, etc.  A CSA model removes a great deal of the speculation.  Also, food service serves as a direct conduit of consumer preference. The intermediaries buy speculatively based on price.  Food service buys to use it directly. Better gauge of usage than commodities markets.

=== Consumer bias

A great benefit of seeking food waste reductions via food service is that the consumer does not reliably estimate their food waste.  They have no systematic way of tracking the multitude of items in their kitchen.
