== Rehabilitating our kitchens

Years of static menu, prepared-to-order food service has ravaged our kitchens. The relentless pressure to deliver freshly prepared food as fast as possible has created a truly dysfunctional culture of stress and strain.

The first piece of the problem is the static menu itself.  Because the preparation of the dishes is the same each day, any originality or insight into the dish is factored out and someone with very little culinary training can simply memorize the steps.  This reduces a task that would otherwise require culinary skills into something more approachable to unskilled labor.

=== Demand volatility

The second issue is prepared-to-order food.  This has two pernicious effects.  First, because the establishment has no control on when customers walk in the door, it is vulnerable to spikes of business.  In fact, one might even say that spikes in customers is the norm, as most people eat at similar times of the day. 

No one likes to wait, least of all a hungry person for their food. Management understands this and places an emphasis on timely service in order to keep their customers happy.  For this reason, spikes in customers translate into spikes of stress for the kitchen. The buffer for this volatility is the work force, they absorb the excess in the form of stress.

=== Labor volatility

Second, prepared to order food leaves kitchens more vulnerable to labor volatility. If a staff member calls in sick, establishments have little means of closing that gap. This translates into additional stress for the remaining kitchen staff as they try to uphold the service expectations. 

For an RF establishment that does the bulk of preparation in advance, there is likely to be more time to fill the gap before the shortage impacts the customer.  Moreover, the RF establishment may be able to cover the gap with additional labor on a different shift, whereas the static menu must find someone to cover the exact shift of the sick employee.  In essence, the RF establishment can average out labor shortfalls with additional labor at a different time.  (Employees may be more likely to be pressured to work when sick due to static menu rigidity.)

=== Blast radius

A final factor in the prepared to order business model is that because each dish is prepared individually, if an employee makes a mistake, only a single dish is affected. What is more, the customer can catch that mistake almost immediately. These dynamics enable the static menu establishment to maintain chronically stressful labor conditions because the impact of mistakes is relatively contained.

For an RF establishment, because many dishes are prepared in bulk in advance, a mistake in preparation will likely affect many more servings and has the potential to go unnoticed for longer.  Ironically, the fact that mistakes are costlier for RF is ultimately a harmonizing factor in food service labor practices.  Because mistakes are more frequent in stressful situations, it means that the worker and the establishments are aligned in their incentives: both want to avoid stressful working conditions. Therefore, business will be strongly incentivized to maintain low-stress working conditions in order to avoid disruptive mistakes.


In effect, the static menu reduces food service to a basic labor commodity and then uses that very same quality to provide further value to the business model.

Establishments seek so desperately to appeal to consumers that they have used unrealistic levels of service and and  cater to the It is important to pause and consider that the 

That so many of us dine out regularly and yet take this fact for granted is a testament to the insidiousness of the culture that has taken hold. 

Indeed, it is at the higher-end, gourmet restaurants that this dysfunction is most pronounced. Consider the recent peer-reviewed study entitled _Alcohol and other drug use in Michelin-starred kitchen brigades_. The highlights from the very first page of article should be enough to give everyone pause:

* Alcohol and other drug (AOD) use appear to be part of the everyday life in Michelin-starred kitchen brigades in Britain and Ireland.

* AOD were found to be used as a means of self-medication and as a coping strategy for most chefs regardless their ranking.

* Alcohol is used to unwind after work and cope with the harsh working environment.

* Drugs and other substances are mainly used to maintain or improve performance. 

That these findings come from the most prestigious establishments in the world implies that this situation arises not for lack of money or expertise.  It cannot be dismissed as a symptom of the low socio-economic standing of the chefs themselves, much less the diners.  It is quite simply a dysfunctional culture of its own creation.  

The idea that this arose from within industry itself is an important realization because it underscores the fact that this dysfunctional system is often rewarded and is seen as a necessary sacrifice, the price of working at the world's finest kitchens.

- Quote Anthony Bourdain


== Gratuity culture

- More stress on the kitchen staff
- Unfairness to servers




