== Guiding principles

The guiding principle of RF is the embrace of nature. This means designing around the resources that are abundant and renewable in the system.  This principle has been largely discarded by the modern food system, however it has sustained our species for countless generations prior to this.  it sustained humanity.

Only in relatively recent history could humans even conceive of reshaping the environment to yield the foods of their choosing.  In this sense, one could say that previous generations had no choice but to live within the constraints of their environment.

Comparing the eating habits of earlier civilizations to our own, the most prominent distinction is their reliance on perennials as compared to our widespread use of annuals.  This is perfectly understandable because perennials do not require replanting each year.  In fact, many perennials grow larger, more resilient and have greater yields with each passing year.  Annuals, as the name implies, must be replanted each year, entailing enormous effort.

Despite the current preference for annuals, there is an abundance of knowledge regarding the use of perennials by people in a wide variety of environments.  Moreover, the integration of perennials into agricultural system that includes annuals has also been studied extensively.  This approach can be broadly grouped under the heading of permaculture, which stands for "permanent agriculture".

Despite the fact that permaculture offers a more efficient way to produce food, it plays a meager role in the modern food system.  This is yet another consequence of the distorted food system.  Though there are many factors at play, one of the most compelling factors is the relative business considerations.  In much the same way that the static menu was motivated by simplicity and uniformity, annual crops have been favored for the simplicity and consistency they offer for the agricultural model.  Because annual crops must be replanted each year, there is relatively little long-term investment required.  If a farmer wishes to increase they output, it is simply a matter of capital investment.  Unlike perennials, that may require years (or even decades) of lead time, annual crops can be rapidly scaled.  This creates an environment of intense competition between farmers, just the type of environment that is desirable by intermediaries.  In this environment, a farmer may simultaneously be a key supplier one year and yet face considerable threat from a much smaller farm due to the potential of a large infusion of capital in that competing farm.  This keeps farms in a state of perpetual angst, ready to cut corners and make compromises lest they fall out of favor of the industry financiers.  In effect, annual crops disempower the farmer in favor or financial powers.  

 Instead, consumers are conditioned to rely on annual crops.  The exact reasons for this phenomenon are complex and interwoven, spanning everything from historical considerations to modern business models.  What can be said, however, is that in the context of our current knowledge and capabilities,the emphasis on annual crops is not warranted.  

An example of a historical driver for annual crop production is the role of wheat in ancient civilization.  Wheat offered a relatively nutrient dense food source that could be stored for months at a time.  This allowed the formation of larger cities and cultural hubs.  Conversely, modern society enjoys means of rapid transport of goods and instantaneous communication.  These factors completely supersede the benefits that humans once derived from being near one another.  In fact, these factors have proven so effective that in some places we now witness an migration from cities to less populated areas. 


 I hope to convince you that this style of food service is qualitatively different than anything we have now, not just offering an incremental improvement to the issues at hand but a whole new landscape of possibility.


