== Guiding principles

The guiding principle of RF is the embrace of nature. This means designing around the resources that are abundant and renewable in the system.  This principle has been largely discarded by the modern food system, however it has sustained our species for countless generations prior to this.  it sustained humanity.

Only in relatively recent history could humans even conceive of reshaping the environment to yield the foods of their choosing.  In this sense, one could say that previous generations had no choice but to live within the constraints of their environment.

Comparing the eating habits of earlier civilizations to our own, the most prominent distinction is their reliance on perennials as compared to our widespread use of annuals.  This is perfectly understandable because perennials do not require replanting each year.  In fact, many perennials grow larger, more resilient and have greater yields with each passing year.  Annuals, as the name implies, must be replanted each year, entailing enormous effort.

Despite the current preference for annuals, there is an abundance of knowledge regarding the use of perennials by people in a wide variety of environments.  Moreover, the integration of perennials into agricultural system that includes annuals has been studied extensively.  This approach can be broadly grouped under the heading of permaculture, which stands for "permanent agriculture".

Despite the fact that permaculture offers a more efficient way to produce food, it plays a meager role in the modern food system.  Instead, consumers are conditioned to rely on annual crops.  The exact reasons for this phenomenon are complex and interwoven, spanning everything from historical considerations to modern business models.  What can be said, however, is that in the context of our current knowledge and capabilities,the emphasis on annual crops is not warranted.  

An example of a historical driver for annual crop production is the role of wheat in ancient civilization.  Wheat offered a relatively nutrient dense food source that could be stored for months at a time.  This allowed the formation of larger cities and cultural hubs.  Conversely, modern society enjoys means of rapid transport of goods and instantaneous communication.  These factors completely supersede the benefits that humans once derived from being near one another.  In fact, these factors have proven so effective that in some places we now witness an migration from cities to less populated areas. 


 I hope to convince you that this style of food service is qualitatively different than anything we have now, not just offering an incremental improvement to the issues at hand but a whole new landscape of possibility.


