== Intensive agricultural practices, "Mass-produced produce"

The effect of distributors is felt beyond farm economics and well into the agricultural practices themselves. On the one hand distributors offer farmers an (effectively) unlimited market. On the other hand, these markets are highly competitive.  Under these forces, farmers are incentivized to produce ever larger quantities of a single crop.  These pressures give way to the adoption of more intensive agricultural practices.

 As already noted, this is not consistent with the laws of nature, and in order to achieve this they must adopt intensive agricultural practices.

These techniques can swiftly and reliably transform the landscape into a highly productive (and profitable) fields.  However, in a long-term these techniques ravage the native ecosystem and result in a precarious livelihood for the farmer. "Widespread adoption of large-scale conventional agricultural production over the last century -- including single crop production, heavy use of synthetic fertilizers and pesticides, and intense tillage -- has contributed to substantial greenhouse gas emissions as well as a decline in soil health, water quality, and biodiversity."

 Farms that use intensive agricultural practices have much higher rates of soil degradation. Neighboring regions can be impacted by fertilizer runoff and pesticide spray. These practices cause in soil destruction this is clearly evident in the quality of the said farmland.

 While notable, pricing is one of the most superficial benefits.  Far more profound benefits are to be found by re-imagining the nature of farming in the context of the new food service paradigm, and to that end, one of the most fundamental questions is: what to grow?

 This rather basic question alludes to an important characteristic of the current food system: that what is grown is not necessarily in the best interest of the farmer or the consumer.  Rather, the decision is influenced by the distributors who seek to _commodify_ the output.  That is, to produce it in ever-more consistent quantities and qualities and under an ever-widening range of conditions.  Such that a tomato from one grower is effectively the same as the next.

 This is driven by the basic nature of the distributors' business model, which is to increase the scale of production of a standardized commodity. But, as noted once already, food is not a standardized commodity.

 In the never-ending pursuit of more standardized agricultural commodities, the following negative practices have become endemic in conventional agriculture: "single crop production, heavy use of synthetic fertilizers and pesticides, and intense tillage" <<yale>>.  These techniques can swiftly and reliably transform the landscape into a highly productive (and profitable) fields.  However, in a long-term these techniques ravage the native ecosystem and result in a precarious livelihood for the farmer.

As the flaws of conventional agriculture have come into clearer focus, a competing approach known as regenerative agriculture has emerged as a strong contender for a more sustainable future. Regenerative agriculture employs a "systems-approach to farming that seeks to improve natural resources rather than depleting them."<<yale>>

With backing from industry-giants like General Mills to renowned-institutions like Yale University, it is widely recognized that it has the potential to remedy the issues plaguing conventional agriculture. The one problem is figuring out who is going to buy the outputs.

RA farms face two challenges when bringing their crop to market. The first is that because RA generally has lower yields than conventional agriculture, the products are more expensive. Second, RA has more diversified outputs, meaning smaller quantities of a given item and greater lengths of time between its next planting <<holden-circle>>.  This does not jive well with an industry that has become accustomed to sourcing large quantities of relatively cheap products.<<circ>>

For this reason, when assessing the barriers to the RA industry, they identified downstream markets as a major barrier <<yale>>. For example, a farmer interviewed for the piece recounted "a friend who contacted over 100 potential buyers for a single specialty crop". 

The new food service paradigm offers a welcome alternative to the existing downstream markets and the challenges they pose.  As noted previously, selling directly to food service, rather than to a distributor, opens up huge margins for the farmer. Furthermore, the specific production practices used by the farmer can be accounted for in the price, whereas distributors are accustomed to thinking in terms of undifferentiated commodities and struggle to incorporate production practices in their pricing <<yale>>.  Finally, the specialty crops can expect a much warmer reception from food service in the new paradigm because the menu can be designed around the ingredient. (Savvy RF establishments will seek to lure customers with "exotic" seasonal ingredients.)

(It is important to note that farmer-restaurant relationships already exist. However, I would argue that essentially those farmers have simply become distributors themselves, along with all of the additional operational complexity that that entails.) __do__ sometimes supply ingredients di


 Much like breaking from a static menu changes the entire nature of food service, so too is the potential for change in the agricultural industry. 

 Perhaps the most important insight of this book is the opportunities that present themselves in the restaurant supply-chain. In this way, consumers can affect the environment. 

 The importance of this new connection between food-service and the farmer cannot be overstated.  Indeed, nearly everything in the remaining book hinges on it.  The closer the relationship that can be forged between these two parties, the more benefits there are to be reaped.
