If society were to adopt RF and consumers increasingly got their meals from food service, it could lead to a proliferation of packaging waste.  The principles of RF do nothing to deter food service from using disposable containers.  Increasing numbers of food service establishments use disposable containers for all their orders, even people dining in.  This keeps the preparation for every order the same and can even be cheaper than cleaning/maintaining reusable servingware. Arguably, disposable containers are only cheaper for the restaurant because it does not bear the externalities of the waste: Increasing evidence suggests that plastic waste is harming our ecosystems and our bodies.

Even though RF is susceptible to the appeal of disposable containers, it enables some advanced developments in food service that could curb the use disposable containers. The challenge with reusable servingware is in the consumer returning it when they are finished.  In the worst case, this ends up being an errand on the other side of town that the consumer must do.

Even in the worst case, one way to lighten this burden is simply by taking more containers on each trip.  In other words, to eat more RF meals.  Because RF is focused on value to the consumer, this is a much more reasonable proposition than increasing consumption of static menu food service.

Increasing the amount of meals a person eats can also facilitate other developments, such as delivery/pick-up.  Milk delivery offers insight into how this could work.  Local dairies sometimes offer delivery service to their customers and use reusable glass containers.  This arrangement requires that the consumer signs up for a regular delivery schedule, which is not unreasonable for a staple ingredient like milk.  On each visit, the driver will deliver the new order and pickup any empty containers left outside. (This is usually facilitated by a designated cooler/box that the customer keeps on their doorstep.) Sometimes the consumer will pay a deposit for the container that is refunded when it is returned.  Additionally, there may be a delivery fee if the order does not meet a minimum size.  Regardless, the key is that the consumer has an ongoing relationship with the dairy.

RF could conceivably follow a similar model, perhaps even more easily than the dairies because for many the desire for prepared meals will be greater than for milk.  This is especially true for smaller households that are increasingly becoming the norm.

== Standardized servingware and RF distributors

The preceding section assumes that the delivery is being handled by the RF establishment itself.  However, delivery could be much more efficient if meals from multiple establishments could be handled by a single entity.  Essentially, this would function as a distributor that could sell food from multiple establishments.

The emphasis that RF places on ready-to-serve food makes this concept much more feasible than the conventional static menu.  Food that must be prepared-to-order or is subject to customization is not amenable to this format.

To make the process most efficient it would require that all the establishments use the same standardized servingware.  This would mean that the delivery vehicle could be designed around the size/shape of the servingware. (Similarly, dishwashers could be designed around this standardized servingware.)

This format offers the best opportunity for reduction in packaging waste.  It means that the consumer could order from multiple establishments while still having a single point-of-contact for the retrieval of the containers.

=== Less startup costs, better competition

The introduction of the third-party RF distributor is desirable from the standpoint of robust market competitiveness.  It means that each individual establishment does not have to invest in the servingware and delivery operations.  This offers a more level playing field in which new-comers can offer the same benefits without large upfront investments.  Effectively, this means the competition between establishments rests on the value of the food they provide and reduces the ability of larger entities to leverage their investment in servingware/delivery to undercut smaller establishments.

Outsourcing the distribution opens up some other interesting benefits for small establishments.

== Less miles, more meals

First of all, there is the increased efficiency of the deliveries.  If food from multiple establishments can be delivered on the same trip, this will reduce the number of trips being made.


The discussion of specialized 
It is clear that 
Recognizing that more frequent purchases facilitate more possibilities

- Delivery and pickup

- Standardized servingware facilitates comparisons between food offerings.

- Automat removes the retail requirement from food serviceLP6008246-DNA_B12.

This can easily turn into a burden for the consumer and deter them from choosing it.  
