If society were to adopt RF and consumers increasingly got their meals from food service, it could lead to a proliferation of packaging waste.  The draw of disposable containers is great and the principles of RF do nothing to deter food service from using disposable containers.  In fact, increasing numbers of food service establishments use disposable containers for all their orders, even dine-in orders.  This keeps the preparation for every order the same and can even be cheaper than cleaning/maintaining reusable servingware. Arguably, disposable containers are only cheaper for restaurants because they do not bear the externalities of the waste: Increasing evidence suggests that plastic waste is harming our ecosystems and our bodies.

Even though RF is susceptible to the appeal of disposable containers, it enables some advanced developments in food service that could curb the use disposable containers. The challenge with reusable servingware is in the consumer returning it when they are finished.  In the worst case, this ends up being an errand on the other side of town that the consumer must do.

Even in the worst case, one way to lighten this burden is simply by taking more containers on each trip.  In other words, to eat more RF meals.  Because RF is focused on value to the consumer, this is a much more reasonable proposition than increasing consumption of static menu food service.

Increasing the amount of meals a person eats can also facilitate other developments, such as delivery/pick-up.  Milk delivery offers insight into how this could work.  Local dairies sometimes offer delivery service to their customers and use reusable glass containers.  This arrangement requires that the consumer signs up for a regular delivery schedule, which is not unreasonable for a staple ingredient like milk.  On each visit, the driver will deliver the new order and pickup any empty containers left outside. (There is usually a designated cooler/box that the customer keeps on their doorstep.) Sometimes the consumer will pay a deposit for the container that is refunded when it is returned.  Additionally, there may be a delivery fee if the order does not meet a minimum size.  Regardless, the key is that the consumer has an ongoing relationship with the dairy.

 The customer is not required to clean the milk jar before returning it. They are simply asked to dump out any remaining milk. The residue after dumping it out still collects at the bottom and sours and turns brown. The dairy does not have a problem with this. Perhaps food containers could be returned "scraped clean", like if they were being loaded into a dishwasher.

RF could conceivably follow a similar model, perhaps even more easily than the dairies because for many the desire for prepared meals will be greater than for milk.  This is especially true for smaller households that are increasingly becoming the norm.

== "Food trucks", Standardized servingware and RF distributors

The preceding section assumes that the delivery is being handled by the RF establishment itself.  However, delivery could be much more efficient if meals from multiple establishments could be handled by a single entity.  Essentially, this would be a local ready-to-serve food distributor that could sell meals from multiple establishments.

The emphasis that RF places on ready-to-serve food makes this concept much more feasible than with the conventional static menu.  Food that must be prepared-to-order or is subject to customization is not amenable to this format.

This format also offers the best chance of reducing packaging waste. Distributors would have a higher sales volume than a single restaurant and would be incentivized to deliver as many meals as possible on a each trip. To make the process most efficient it would require that all the establishments use the same standardized servingware.  This would mean that the delivery vehicle could be designed around the size/shape of the servingware. (Similarly, dishwashers could be designed around this standardized servingware.) In this strategy, reusable servingware actually has an edge over disposable packaging because the latter is often flimsy, prone to leakage and is not designed to be transported in bulk.  

This format means that the consumer could order from multiple establishments while still having a single point-of-contact for the retrieval of the containers.

== Going in circles

- Conventional delivery does not know what customers will order and cannot prepare it far in advance.  As a result, delivery drivers sometimes make multiple trips to the same neighborhood. RF delivery is more like small-parcel delivery in which a driver delivers several meals when passing through a neighborhood.

=== Less startup costs, better competition

The introduction of the third-party RF distributor encourages free-market competitiveness.  It means that each individual establishment does not have to invest in servingware and delivery operations.  This offers a more level playing field in which new-comers can offer the same benefits without large upfront investments.  Effectively, this means the competition between establishments rests on the value of the food and reduces the ability of larger entities to leverage their investment in servingware/delivery to undercut smaller establishments.

Outsourcing the distribution also opens up some other interesting benefits. In the conventional model, food service is located in retail storefronts where the cost of property can be quite high.  The consumer, of course, bears this cost. A distributor would allow establishments to have no retail store front at all, operating solely out of industrial kitchen space. Taking this further, RF distribution allows for pop-up/seasonal food service in which commercial kitchen space is rented for a short period of time ("cloud kitchen").  RF gives society the adaptability to take advantage of any situation.

== Less miles, more meals

The idea of local ready-to-serve food distributor is topical because of the recent emergence of the food-delivery industry.  This industry piggybacked on the ride-share industry.  It allows many restaurants to share one pool of delivery drivers and for meals from different establishments to be delivered by the same driver. In these respects it is a great efficiency improvement.

Unfortunately the state of static menu food delivery is so horribly inefficient that these efficiency improvements still offer nothing comparable to an RF distributor.  

- Meals are still prepared individually and often delivered individually.  With RF distributors, dozens of meals could be picked up at a time.  Delivery services would make many trips back and forth to achieve the same volume.  

- Food delivery services require real-time communication between customers, establishments and drivers.  In turn, this requires complex software that drives up the price of this service.  With RF distributors, the pickup from the restaurant could be scheduled well in advance and potentially so could the deliveries to the customers (much like the milk delivery).  This reduces complexity allowing distributors compete on the actual distribution of food and reducing the ability of large entities to leverage sophisticated software against competitors. Further, some food delivery services require that the establishments keep a dedicated device/tablet to communicate with their data center.  This tactic, while ostensibly providing a helpful means of facilitation, also serves to ensure market dominance by increasing the transaction costs of an establishment wishing to change delivery services (e.g. vendor lock-in) and also increases the investment required for competitors to enter the market.  Both of these factors limit market competitiveness and hurt the consumer.

- Specialized vehicles cannot be utilized.

- The food delivery industry, like the ride-share industry, is gig work. This form of employment is prone to worker exploitation.  It is essentially low-skill labor that almost anyone can do;  If you have ever picked up takeout for your family, then you are qualified to be a driver for a food delivery service. On the other hand, an RF distributor would offer better employment because it is more highly-skilled labor to operate/load/unload a specialized vehicle.  While gig work has the advantage that the labor pool can be easily scaled up at peak times.  RF on the other hand seeks to flatten the peak with wider delivery windows and relies on its greater efficiency to meet peak demands.

The following are several ways that RF delivery is more efficient.

- More meals can be delivered in a single trip because the food can be prepared in advance.  Most static menu foods suffer greatly if not consumed shortly after they are prepared.  Combine this with the fact that customers are able to choose from a wide variety of items and can further customize each item and there is virtually no possibility left to predict what customers will order.  

- Conventional delivery is based on the idea that the food is delivered ASAP.  That is, as soon as it can be prepared and brought to your doorstep.  Ironically, this does not mean that the food will arrive quickly or in a predictable time-frame.  Thus, the consumer does not know exactly when they will get their food even though it is all designed around their convenience.  RF certainly could compete on quickest delivery but prefer to leverage its business model to focus on efficiency and value rather than convenience.  This means that customers would be offered the ability to order their food well in advance of their intended meal time and would receive a delivery window of a couple hours that included their ideal meal time.  This allows RF the best opportunity to deliver multiple meals on the same route.

, longer than what you would expect if you ordered from the static menu.  


First of all, there is the increased efficiency of the deliveries.  If food from multiple establishments can be delivered on the same trip, this will reduce the number of trips being made.


The discussion of specialized 

- Delivery and pickup

- Standardized servingware facilitates comparisons between food offerings.

- Automat removes the retail requirement from food service

This can easily turn into a burden for the consumer and deter them from choosing it.  

== 3rd party returns

Apart from a delivery/pickup service, there could be deposit locations to return the servingware, like mailboxes.  They couldn't be installed on the public sidewalk like mailboxes.  But certain private businesses that have no competing food interest might find the increased traffic desirable. For example, a car wash might get extra customers. 

== Static menu participation
