== Delivery

What can we learn from the humble delivery driver? For decades, pizza delivery has represented a sector of the employment market.  It is so ubiquitous and it takes such a familiar form that is easy to take it for granted.  Yet, delivery is a somewhat unusual niche of the market.  The first thing to note is that delivery drivers always drive a normal civilian vehicle, not a specialized truck.  The second thing to note is that the drivers themselves own the vehicles, not the company.

The first aspect should be a dead giveaway that something is off about the situation.  In virtually every other industry with a significant delivery component, drivers use specialized vehicles that allow them to efficiently transport large quantities.  

The lack of specialized delivery vehicles is not an oversight of the industry.  Rather, it is an admission of its overall inefficiency.  A specialized vehicle that could hold more meals would be of no benefit because there is no way to know in advance what meals will be ordered.  Each order is effectively unique and there are so many possible combinations that you could not hope to load a truck with hundreds of pre-made meals and thereby avoid return trips to the depot; Eventually you would run out of one of the varieties necessitating a return to the depot.


Rudimentary insulation, if at all, is sufficient. The idea of an actual warmer or refrigerator on board is unheard of.
