== Home Economics

To better understand what a quick, healthy and affordable meal could mean to us today, it is helpful to look at how our diet has changed over the past 50 years.  In doing so, what becomes apparent is that a quick, healthy and affordable meal was not necessarily available to prior generations either.  Yet, at the same time, it arguably did not present the same issue that it is for us today.

Prior to the seventies, the majority of meals were prepared in the home. At that time, a typical household would have working-age males part of the labor force, while their female counterparts stayed at home attending to domestic duties.  Of these duties, preparing meals for the family would have been at the forefront.  It is estimated that the average house-wife spent upwards of three hours per day in the kitchen.  This was before the advent of processed foods so meals were based around whole foods.
While we certainly wouldn't call these meals "quick", on the whole it was still a very reasonable proposition because home ownership and all the other trappings of middle-class life were perfectly attainable for a single-income family.  Furthermore, families were larger during those days, and because cooking for more people often requires only a marginal amount of extra work, the home cooked meal was an eminently economical option.

_There are several key trends that occurred over the past fifty years that impacted our relationship with food.  These are smaller family sizes, a declining middle-class, and the rise of the processed foods industry._

Beginning in the 1970's, processed foods began to enter the scene. These foods were high in sugar, fat. These foods were addictive, concentrated with highly refined ingredients. The companies manufacturing them were powerful and were subsidized by the government. The food could stay on the shelf for a long time.The quality of food declined and Americans became obese. During this time the price of bad ingredients like grain dropped while the price for fresh fruits and vegetables doubled.

Over a relatively short period of time, the United States experienced an explosion in obesity with its myriad associated health complications close behind _began to dominate the medical industry_.  The needref declared that non-communicable diseases were the number one cause of death in the United States. The problem was further compounded by the business tactics employed by the food producers themselves.  In a relentless pursuit of greater profits (and, in turn, shareholder value), these companies used aggressive marketing tactics targeting children and encouraging consumption. They also increased portion sizes, further encouraging consumption.

By the late nineties, the obesity epidemic and the cadre of powerful companies driving it prompted comparisons between another major public-health campaign of the times: cigarette smoking.  _the public health efforts engaged in the fight_ against smoking _and the tobacco companies_. 

The parallels are indeed chilling.  Researchers drew striking similarities between cravings for junk food and the cravings experienced by drug addicts and likened compulsive eating to behaviors exhibited by addicts, even demonstrating via MRI that the cravings for sugary items such as a chocolate milkshake stimulate similar brain pathways as those of alcohol and narcotic addiction.

Further, advertising and marketing targeting children and youth was a key strategy of both industries.

Not surprisingly, then, many of the same tactics that were successfully employed in the public health campaign against smoking have been proposed in the battle against obesity.

In the _Lancet_ series on obesity in 2011: "Policy and regulatory actions were identified as the most effective and cost-effective means of tackling the problem."

Sadly, just seven years after this careful assessment and its accompanying recommendations were put forth, the _Lancet_ organized a second series on obesity.  The key motivation this time was to "ask what else is needed" to combat the rising trends in obesity that had continued largely unperturbed during the intervening years. 

The second _Lancet_ meeting did not actually propose new approaches to tackling the situation as much as it identified the existing ones which had shown promise and refined the overall framing of the issue. 

What perplexes policy-makers is the varied nature of obesity drivers.  With tobacco the issue was black-and-white.  Cigarette smoking was an evil in the truest sense, without any redeeming qualities of its own.  Cravings for cigarettes are driven by nicotine addiction and not any innate biological process. 

But junk food is not the same as cigarettes, nor is the body's natural preference for energy-dense foods the same as nicotine addiction.  While smoking represents a clearly defined risk, unhealthy foods are generally only a risk when consumed in excess.  Furthermore, whereas nothing can satiate a smoker except a cigarette - even nicotine patches are not effective, cravings for junk food can be virtually nullified simply be eating something else.  As such, a continual challenge in addressing obesity is doing it in a targeted and effective manner.

Consistent with this assessment, the areas where policy-makers have been able to make headway are distinguished by the presence of a narrowly defined threat in an institutional setting _with high-risk groups_.  For example, the banning of junk food in schools has been instituted in many schools throughout the world with great success.  It consistently receives strong support from stakeholders due to the fact that childhood obesity has been shown to be particularly damaging to long-term health and the recognition that schools have a custodial duty to provide a healthy environment for the students. 

By contrast, in broader society many like-minded policy efforts are met with fierce resistance from industry groups or are diluted to such an extent as to be almost ineffectual.  As critics have pointed out, these policies are often applied inconsistently.  For example, while it may seem easy enough to propose a tax on candy bars due to their high sugar content, does that tax also apply to a wedding cake?  Goodhart's law states that "when a measure becomes a target, it ceases to be a good measure", and is a sobering reminder of the difficulty in this matter.  

Perhaps what is most perplexing is not the failed attempts of policy-makers but the fact that they were needed in the first place.  In the words of one researcher, why do people "fail to make decisions in their own self-interest"?

From the extensive analysis of the issue and comparisons of different interventions, we can gather that economic interventions are particularly effective.

When reading any of the literature on the subject it is a foregone conclusion that the private sector does not have what it takes to stem the obesity epidemic, or at least not without being incentivized to do so.

A key summary to emerge from this second meeting was titled "Pockets of progress" in reference to the "flattening of childhood
obesity in some cities and countries where rates were already high". Apart from those "pockets", the obesity epidemic had proceeded largely unperturbed.

When approaching a challenging issue like obesity, a natural way to seek to understand it is to dissect the different _risk_ factors at play.  As we've already seen changes in everything from home-cooked meals and smoking all the way to labor wages and government subsidies can be correlated with obesity. Oftentimes a detailed study of such factors can yield insights and ideas for solutions, or ways to augment the system.

However, sometimes solutions are not _apparent_ to be found in these factors. And in the process of increasingly detailed interrogation of these factors, there is the danger that these factors become absolutes in the mind of the researcher.
