= Food for Thought

== Outline

* How it all started
** The question: what to have for dinner
* How did we come to have an unhealthy diet and what is it doing to us?
** most meals were cooked at home in the 1960s
** processed foods, subsidies and marketing


== What to have for dinner?

It all started with a question that you are probably familiar with: “What should I have for dinner?”.  I wasn’t asking it any sense of food security, like whether I would have dinner at all.  No, this was more about what to choose among a multitude of options.  On the surface, it almost seems like a dream come true (and to many less fortunate it is), but in actuality it was marked by a note of frustration, frustration that even amidst a sea of options, none seemed to offer what I was looking for.

The trouble I found was that I was always struggling to balance three factors: time, cost, and nutrition.  I wanted a quick, affordable and healthy meal, and it just wasn’t available.  If I prepared food at home, I could have a very healthy and affordable meal, but the time it would take was often more than I wanted to commit to, particularly on a weeknight when time was already scarce.  On the other hand, eating out (or getting food to-go) offered the perfect antidote for the time-starved, but it came at a severe compromise on the other fronts: the cheaper food was usually less nutritious and the more expensive food was, well, more expensive.  

Over time, this very basic observation about home economics came to fascinate me as I realized that its effects were felt well past the personal frustrations of what to eat for dinner.  Reflecting on the state of health care, environmental sustainability and poverty (just to name a few), I was surprised to find how many of the problems that plague modern society were linked to the lack of quick, affordable and healthy food.

The second and equally captivating factor is that, in the current digital age, it seemed that there were more possibilities to address the issue than ever before.

 This little, innocent question about what to have for dinner are actually tied to some of the most serious health and environmental concerns of our day._

 That in itself was not very interesting, but the fact that this problem affected so many other people and that it tied into so many serious health and environmental concerns is what really captivated me.

== Opportunities for quick, affordable and healthy meals ("The invisible hand and the blind spot")

 In a very real sense, to even suggest that a quicker, cheaper and healthier meal might be possible risks coming off as naive, even more so to suggest that it is possible without any dramatic intervention in the economy.  We all know the power of the free markets and their ability to deliver goods and services at competitive prices to meet virtually any imaginable desire.  And, surely, there is plenty of competition in today's food service industry as well as plenty of demand for quicker, cheaper and healthier food in society. Therefore, if the necessary market conditions exist and yet we do not see quicker, cheaper and healthier food being offered, then theory tells us that there is something else, some other constraint on the system, that is preventing the market from meeting the demand.
 
 For example, some may argue that is is not possible because healthy ingredients are too expensive. (This is not the case but could be mistaken as such.) 

 Barring any dramatic intervention in the economy, they would claim that you could not profitably operate such a business __on such margins__. 

When it comes to the question of creating dramatically quicker, cheaper and healthier food, many would say it's impossible.  They would point to the sophisticated logistics of just-in-time supply chains, the competition in the industry, and the ever-expanding offerings of "light" menu items as evidence that the full weight of the industry is already behind this effort.

It is not that these dynamics are false, but the assumption that such industry dynamics always lead to an optimal economy is. While some commodities may be guided toward efficient production by the "invisible hand" of the free markets, food is not one. 

 All of these things are true, but the argument is based on a flawed assumption: that (given sufficient time) the market will always find a way to supply a demand.  This is a pretty safe assumption for most things, but food is not most things.  

For one thing, food, or more specifically, the value of food, is a highly subjective measure.  It is intertwined with culture, causing some foods to be valued higher due to tradition.  Even within the same person, the value placed on a certain type of food is far greater when they are craving it versus 20 minutes after they have eaten it. 

In turn, this subjectivity has clouded the waters just enough to prevent a careful assessment of the food-service landscape.  This is a major problem because the landscape has changed dramatically over the past 50 years.

We are caught in what is sometimes referred to as path dependency, a phenomenon in history where society continues to do something simply because it is the way things have been done before, even despite a change in the prevailing conditions that gave rise to the original behavior.  The inherent risk of something new is sometimes a factor, however, it can also be caused by less tangible factors like culture and tradition.  

 It most often arises when there are considerable costs associated with changing the practice.  

Ultimately, regardless of the forces driving it, path dependency manifests itself as a sociological phenomenon such that even individuals without any ties or investment in the existing practice will not attempt to alter it.  In other words, the practice persists because it is the accepted way of doing things, not because it is necessarily the best way, almost as though there were a collective blind-spot in the market.

 In what follows, I will make the case for the claims above, showing not only that quicker, cheaper and healthier food is possible but that it would have enormous benefits to society.

== Spoiled for choice

If the ultimate goal of this book is to change the reader's outlook of the possibilities for quick, cheap and healthy food in food service, then there is no better way to start than to juxtapose conventional food-service with with the depression-era soup kitchen.  While this is not the vision for modern day food service, it serves to highlight several important characteristics.

 In a very real sense, to even suggest that a cheaper, healthier meal might be readily available risks coming off as naive.  We all know the power of the free markets and their ability to deliver goods and services to meet virtually any imaginable desire.

 The canonical value-oriented restaurant is the soup kitchen. Known from the depression years, soup kitchens are society's response to difficult times.

 Perhaps it is a desire to push the memory of these difficult times into the past that keeps us from recognizing the lessons they can teach us even in more fortunate times.

 The soup kitchen format is eminently efficient. Born of tough times, when food was a matter of survival, the soup kitchen was the social intervention tasked with closing the gap.


The foremost characteristic is the fact that everyone eats the same dish at a soup kitchen.  This is not too different from how many families eat at home, but it is almost the complete opposite of the food service industry, in which each person is able to choose from many different items.

The second most important characteristic of a soup kitchen is that the food is not prepared to order.  Again, this contrasts sharply with the food service industry in which there is almost an implicit expectation that the food will be prepared to order.  Indeed, some restaurants boast of how each dish is prepared-to-order, believing that it serves as a mark of quality in their operation.

Finally, a soup kitchen freely varies its menu in response to cost and availability of ingredients. On the other hand, most restaurants have the same menu with the same dishes for years. This is ingrained in the business model and encourages restaurants build their brand around certain dishes and types of cuisine.

These three factors, seemingly rather innocuous, shape the food service landscape in surprising and far-reaching ways.  They will be referred to as the static menu business model.  

 To get a better understanding of the dynamics, the following sections will consider their role in some common food service scenarios.  This will also serve as an opportunity to introduce some of the issues that have arisen as a consequence.

 Moreover, in limits the number of people that can be served (rate of sale) because each dish must be prepared individually no matter how many customers are waiting.  This also drives up the labor costs because while food that can be prepared in advance  prevents the operation some foods can be prepared in large quantities  vulnerable to waste of from dishes going cold. 

 These three factors combine to severely limit the scale and efficiency of food service.  Were it just one of them, perhaps it could be balanced out by other considerations, but the wholesale embrace of this __modus operandi__ leaves no possibility of substantive change in the industry.

 For example, the allowance of customization is not a very big sacrifice if you are already preparing a dish to order.  And, in turn, preparing each dish to order can make sense if you have a variety of dishes and an unpredictable rate of sale.

