= Food for Thought

== Outline

* How it all started
** The question: what to have for dinner
* How did we come to have an unhealthy diet and what is it doing to us?
** most meals were cooked at home in the 1960s
** processed foods, subsidies and marketing


Blank section

== What to have for dinner?

It all started with a question that you are probably familiar with: “What should I have for dinner?”.  I wasn’t asking it any sense of food security, like whether I would have dinner at all.  No, this was more about what to choose amongst a multitude of options.  On the surface, it almost seems like a dream come true (and to many less fortunate it is), but in actuality it was marked by a note of frustration, frustration that even amidst a sea of options, none seemed to offer what I was looking for.

The trouble I found was that I was always struggling to balance three factors: time, cost, and nutrition.  I wanted a quick, affordable and healthy meal, and it just wasn’t available.  If I prepared food at home, I could have a very healthy and affordable meal, but the time it would take was often more than I wanted to commit to, particularly on a weeknight when time was already scarce.  On the other hand, eating out (or getting food to-go) offered the perfect antidote for the time-starved, but it came at a severe compromise on the other fronts: the cheaper food was usually less nutritious and the more expensive food was, well, more expensive.  

Over time, this very basic observation about food economics came to fascinate me as I realized that its effects were felt well past the personal frustrations of what to eat for dinner.  Reflecting on the state of health care, environmental sustainability and poverty (just to name a few), I was surprised to find how many of the problems that plague modern society were linked to the lack of quick, affordable and healthy food.

The second and equally captivating factor is that, in our current age of information technology, it seemed like there were more possibilities to address the issue than ever before.

_To bring that altogether in a more relatable way, if you have a busy schedule, are on a tight budget and also wanting to eat healthy (or worse, keep to a diet), you very well may find yourself in a precarious situation come dinner-time, and that realization was what initially captivated my interest in this topic.  Because the unfortunate truth is that that trio of conditions describes a great deal of Americans, and the ramifications of this little, innocent question about what to have for dinner are actually tied to some of the most serious health and environmental concerns of our day._

_That in itself was not very interesting, but the fact that this problem affected so many other people and that it tied into so many serious health and environmental concerns is what really captivated me._

== Opportunities for quick, affordable and healthy meals

In a very real sense, to even suggest that a quicker, cheaper and healthier meal might be possible risks coming off as naive, even more so to suggest that it is possible without any dramatic intervention in the economy.  We all know the power of the free markets and their ability to deliver goods and services at competitive prices to meet virtually any imaginable desire.  And, surely, there is plenty of competition in today's food service industry as well as plenty of demand for quicker, cheaper and healthier food in society. Therefore, if the necessary market conditions exist and yet we do not see quicker, cheaper and healthier food being offered, then theory tells us that there is something else, some other constraint on the system, that is preventing the market from meeting the demand.

Thus, when it comes to the question of creating dramatically quicker, cheaper and healthier food, many would say it's impossible, that you could not operate a business on such margins. They would point to the sophisticated logistics of just-in-time supply chains, the competition in the industry, and the ever-expanding offerings of "light" menu items as evidence that the full weight of the industry is already behind this effort.

All of these things are true, but the argument is based on a flawed assumption: that (given sufficient time) the market will always find a way to supply a demand.  This is a pretty safe assumption for most things, but food is not most things.  

For one thing, food, or more specifically, the value of food, is a highly subjective measure.  It is intertwined with culture, causing some foods to be valued higher due to tradition.  Even within the same person, the value placed on a certain type of food is far greater when they are craving it versus 20 minutes after they have eaten it. 

In turn, this subjectivity has clouded the waters just enough to prevent a careful assessment of the food-service landscape.  This is a major problem because the landscape has changed dramatically over the past 50 years.

We are caught in what is sometimes referred to as path dependency, a phenomenon in history where society continues to do something despite a change in the prevailing conditions.  It most often arises when there are considerable costs associated with changing the practice.  However, it can also be caused by less tangible factors like culture and tradition.  

Ultimately, regardless of the forces driving it, path dependency manifests itself as a sociological phenomenon such that even individuals without any ties or investment in the existing practice will not attempt to alter it.  In other words, the practice persists because it is the accepted way of doing things, not because it is necessarily the best way, almost as though there were a collective blind-spot in the market.

In what follows, I will make the case for the claims above, showing not only that quicker, cheaper and healthier food is possible but that it would have enormous benefits to society.

== Spoiled for choice

If the ultimate goal of this book is to change the reader's perception of the existing food service landscape, then there is no better way to start than to juxtapose it with with the depression-era soup kitchen.  While this is not the vision for modern day food service, it serves to highlight several important characteristics.

The foremost characteristic is the fact that everyone eats the same dish at a soup kitchen.  This is not too different from how many families eat at home, but it is almost the complete opposite of the food service industry, in which each person is able to choose from many different items.

The second most important characteristic of a soup kitchen is that the food is not prepared to order.  Again, this contrasts sharply with the food service industry in which there is almost an implicit expectation that the food will be prepared to order.  Indeed, some restaurants boast of how each dish is prepared-to-order, believing that it serves as a mark of quality in their operation.

Finally, a soup kitchen freely varies its menu in response to cost and availability of ingredients. On the other hand, most restaurants have a static menu, with the same dishes on the menu for years. This is ingrained in the business model and encourages restaurants build their brand around certain dishes and types of cuisine.

These three factors, seemingly rather innocuous, shape the food service landscape in surprising and far-reaching ways.  To get a better understanding of the dynamics, the following sections will consider their role in some common food service scenarios.  This will also serve as an opportunity to introduce some of the issues that have arisen as a consequence.

 Moreover, in limits the number of people that can be served (rate of sale) because each dish must be prepared individually no matter how many customers are waiting.  This also drives up the labor costs because while food that can be prepared in advance  prevents the operation some foods can be prepared in large quantities  vulnerable to waste of from dishes going cold. 




=== Alternative ending

These three factors combine to severely limit the scale and efficiency of food service.  Were it just one of them, perhaps it could be balanced out by other considerations, but the wholesale embrace of this __modus operandi__ leaves no possibility of substantive change in the industry.

It is worth noting that there can be a great deal of interplay between these factors, so much so that one could quite convincingly argue that they are in fact a single phenomenon.  For example, the allowance of customization is not a very big sacrifice if you are already preparing a dish to order.  And, in turn, preparing each dish to order can make sense if you have a variety of dishes and an unpredictable rate of sale.

This, however, is more a statement of current food service than it is of any intrinsic relationship between these factors.  As will become apparent, each factor is very much an independent consideration despite the fact that they appear so interconnected in the industry today.

== Menu & supply chain

Most restaurants in America have a menu with a variety of items and it stays mostly the same year after year. This is what will be referred to as a static menu.  __This is the concept of the static menu that was introduced earlier.__
- This intent is evident in fancy menus with photography and professional printing; They intend to keep the menu the same for a while.

The static menu is popular because it facilitate a simple business strategy: specializing in a handful of dishes. The inventory and the recipes are always the same and customers know what to expect. It makes the business manageable at a very small scale, even with just a single person.

__The challenge of a static menu is obtaining the fresh produce year-round.__ Where the static menu falls short is in relation to fresh produce. A given ingredient will only be in season for part of the year, so in order to keep the menu consistent, restaurants must rely on distributors that can source ingredients from different parts of the globe. 

This is convenient not just because it makes the concept of the static menu feasible, but also because the distributors often serve as a single point of contact for a variety of other ingredients, beyond just the produce that necessitates them.

The catch is that produce sourced from a different part of the world is not the same as locally-grown produce; It is likely to be more expensive and less fresh.

__At the minimum, there are the costs of transport, sometimes called "food miles", to consider. But more often this is accompanied by other factors, such as waste and diminished quality.  As a rule, the more perishable the produce, the more likely it is that the upstream growing techniques will be altered to mitigate spoilage, such as picking produce early.  These techniques almost always result in lower quality.__

Neither is the trouble over once the produce is in hand.  Spoilage is a big factor in restaurants and the static menu prevents changing the menu or the price, leaving restaurants with little means to combat impending spoilage __and further discouraging incorporation of fresh produce in the menu__.

In summary, fresh produce introduces variability in cost and quality into the static menu business model.  Moreover, the static menu leaves little opportunities to adapt to the variability. Thus, on a theoretical level, we would expect the role of fresh produce to be minimized/limited in static menus. This is consistent with what is observed in reality in which processed ingredients form the bulk of what is served.


__the convenience of obtaining an off-season ingredient comes at an added cost.  Moreover, this cost fluctuates throughout the year. Combined with concerns of spoilage, these factors discourage the use of fresh produce in a static menu.__

__Ultimately, the additional costs and their inherent volatility discourage the use of __

__, which is in turn passed on to the consumer__ __doesn't mean that they are insulated from price fluctuations__.  

== Plan to fail or plan to scale

Another common characteristic of the food service industry is a menu of prepared-to-order food.  Indeed, preparing food to order is often seen as a symbol of quality in the operation. Furthermore, preparing food to order often offers the opportunity to customize the dish. 

The consequences of preparing food to order come in the form of scale and efficiency.  Because each dish must be prepared individually, there is very little drop in marginal labor cost when preparing larger quantities.  Nor is it quick to prepare such food in large quantities, sometimes leading to long waits.  This is exacerbated by consumers having the option to customize their dishes, meaning that even when multiple orders for the same dish are received, the cook may not be able to make a bigger batch due to relatively minor things like differing spice levels or protein selection.

Compare this to a restaurant with a single, ready-to-serve dish. There is no comparison, so to speak. This approach is so much more efficient that it not only has the potential for massive reductions in marginal cost, it also does not suffer from long waits at peak times because, by definition, the food requires minimal prep before serving and there is no question about what will be ordered nor customizations to it. 

- __experiences none of the issues of the common, prepared-to-order restaurant.__
- __Certain dishes can even take advantage of industrial-scale equipment, offering enormous reductions in marginal cost.  Further more, there is no requirement that the equipment even be located at the point-of-sale.  It could just as easily be located off-site with the point of sale responsible only for minimal final preparation and serving.__


== Upstream effects of menu choice

The previous section examined common restaurant characteristics and their shortcomings in regards to efficiency and disincentives towards fresh produce. Finally, it contrasted that with an RF-inspired restaurant that serves only a single, ready-to-serve dish.

It has already been noted that the RF-style of restaurant will be much more efficient at preparing and serving the food. This section goes further and considers the unique opportunities that arise before the food is even delivered, opportunities in the supply chain.

The supply chain of a static menu restaurant was touched upon earlier and it was noted that distributors play a critical role in their supply chains due the static menu business model. By the same token, a restaurant that does not rely on a static menu also does not need to rely as much on distributors. 

To understand this more clearly it is helpful to introduce the concept of transaction costs. Each item that a restaurant needs requires an investment of time to arrange and execute the sale. This is the transaction cost. The amount of time it requires can vary widely. Transaction costs can vary widely between different vendors. For example, getting produce direct from the grower often entails high transaction costs relative to a distributor.  Everything from availability, to ordering to billing will likely be much more streamlined with the latter.

For a static-menu restaurant, in particular, sourcing each type of fresh produce directly from the farmer would result in extremely high transaction costs relative to a distributor.  This is a combination of two factors.  

- The static menu requires a consistent supply of produce year-round, requiring multiple growers in different geographic regions to achieve a consistent supply of each ingredient.
- The static menu offers a wide variety of dishes, which increases the number of different ingredients, requiring additional growers to obtain all the different types.

Finally, it is important to emphasize that despite the variety of produce required by the static menu, the overall amount of produce used in the menu is minimal relative to meat and grains. Because transaction costs are often fixed costs, they can quickly outweigh other factors when quantities are small. This is important because a grower __can__ offer substantially lower prices, however the static menu restaurant likely cannot purchase a large enough quantity for the cost savings to outweigh the transaction costs.

Effectively, it is a case of cutting out the middle-man. This may not mean much to a static menu restaurant, but an RF restaurant could leverage the reduced cost of raw ingredients very effectively.  It would be able to tailor the dishes specifically to those ingredients and to adjust the price to incentivize sales. 

Another advantage of an RF restaurant is that is relies on prepare-in-advance dishes.  In general, such dishes have significantly lower marginal labor cost, meaning that the ingredients account for a larger proportion of the overall cost.  Therefore, savings in produce cost by sourcing directly from the grower can more substantially reduce the marginal cost of the final product in an RF-style restaurant. For a high-volume business, this could be even be more valuable than increased sales. 

 In turn, savings in this area are more significant.  

 This is not only a reflection of how much convenience is offered by distributors; It is also a reflection of how little fresh produce is used and how rigidly it fits into a static menu.  If, on the other hand, we consider a restaurant in the new paradigm, one that is able to tailor their day's menu to a given ingredient and is capable of serving large volumes of food, the benefits of sourcing local ingredients could be enormous, even despite the transaction costs.  This is because a large enough quantity of a single ingredient is being used that the savings from cutting out the distributor outweigh the increased transaction costs. 

 When the static menu was introduced, the distinction between globally sourced produce versus locally grown produce was made.  This made it seem as though the locally grown produce would be an obvious choice when available, but in practice even that is not so. 

 Businesses will still need a distributor for other things and the extra time it takes to arrange a separate order for a couple of local ingredients can be a deal-breaker __barrier to the entire transaction__.

== Why static menu dislikes fresh produce

It has been noted that static menus do not incentivize the use of fresh produce. This section explores this phenomenon through a chain of cause-effect relationships.

The initial driver comes from the desire for a simple business model. A static menu means that the establishment can specialize in a handful of dishes. Menu-planning occurs once in the beginning, rather than being an ongoing task. By extension, the marketing and sales strategies need not change since the product does not change.

The consistency offered by the static menu means that customers have a clear expectation of what is offered.  Things are predictable.

Within this context, it is obvious that having a constant price for the dishes perfectly completes the model.  It would be a shame if a customer came for their favorite dish only to find that it was too expensive that day. Furthermore, it is natural for the customer to expect the same item to cost the same from day-to-day; Most goods behave in this manner.

Fresh produce availability, on the other hand, can vary widely over the course of the year.  The more perishable the ingredient and the more seasonal it is, the greater the variability.  This can be the difference between getting an item directly from a nearby grower for a bargain in-season and getting it from half-way around the world a few months later.

In theory, there is no reason why the menu items couldn't vary in price according to their constituent ingredients. However, this flies in the face of the static-menu mindset. Recall, the motivating force behind the static-menu is simplicity and predictability, but changing the price according to market rates is far from trivial. It would first require calculating the price - surely entailing a spreadsheet, at minimum - then the price change must be updated on the menu, and still the customer would not know any of this until visiting. And then how often would this need to be done?

One might argue that you could simply average of cost of the produce for the year and then keep the price consistent. In practice, this is likely to be rather difficult.  First off, the price cannot be perfectly predicted. A cursory look at commodities markets should convince anyone that prices are far from predictable. Second, the more perishable and seasonal the ingredient, the more it can be affected by aberrations such as natural disasters. Finally, if there is any seasonality in the sales of the food, then that too must be predicted and incorporated in the calculation. 

Finally, should the business owner succeed in perfectly averaging out the cost of ingredients over the year, all they will have achieved is consistency for the consumer.  Indeed, to the extent that they stabilize the cost to the consumer, it is their own finances that are the buffer, resulting in fluctuating profit margins throughout the year and complicating financial analyses.

Therefore, to achieve the final piece of the static menu business model, a consistent price, fresh produce is marginalized because it represents financial uncertainty and complexity. 

=== Always in stock

Another hallmark of the static menu business model is that all items are always in stock.  Of course, this is desirable for a consumer because they never have to worry that their favorite dish will be sold out. It can even risk giving the impression of a poorly run establishment if menu items are sold out. 

But to keep all items in stock means having sufficient inventory at all times for your highest possible sales.  This may be a trivial requirement or a crushing burden depending on the model of the restaurant.  The two key factors that determine the impact are 1) how perishable the ingredients are and 2) how many items are on the menu.

We have already established that the static menu almost always offers a variety of different dishes.  Therefore, to achieve the "always available" component of the business model, the static menu favors meat and grains and other processed ingredients, which are less perishable than fresh produce. This translates into less waste when sales aren't at their peak. As an added benefit, meat, grains and other processed foods tend to be more nutrient dense, meaning less storage space is required for the excess inventory.

== Prep times

The situation gets worse when we compare fresh produce to meat and grains in terms of preparation.

== The tipping point

 Not really a tipping point
The previous section introduced a tipping-point, the point at which a restaurant can sell enough of a single fresh produce ingredient that it becomes economical to source it directly from the grower. The defining characteristic of a tipping is not just that one side now outweighs the other, it is that the fundamental forces now also favor the other. 

The significance of this event cannot be overstated.  For once, fresh produce will represent a strategic opportunity in the business model.  Restaurants will be incentivized to use as much of the locally sourced ingredient as possible because they will be obtaining it at wholesale cost and the transaction cost is fixed.  That will result in menu items that incorporate much more produce than in the average person's current diet.

This marks the point where we are firmly on the road to healthy, affordable and convenient food service.  Up until this point, the principles discussed (e.g. efficiency) could be applied to any food service, but it is the application of these principles in order facilitate the use of fresh produce that represents the beginning of possibilities in the new paradigm. 

