== Renaissance

The Renaissance is best remembered for the stunning works of art and sculpture and paintings by the likes of Rembrandt.  However the Renaissance is best understood as a shift in thinking about life itself, with the paintings that have been handed down to us from that time representing a manifestation of that new way of thinking.

Similarly, the food Renaissance I have been arguing for transcends the ingredients, the recipes and the restaurant itself and is an expression of the connection between human life and the environment. 

a second key understanding about the Renaissance is that this shift in thinking did not represent a new way of thinking. in fact the term Renaissance means rebirth and refers to the fact that these ideas were prevalent in Greek society. similarly the food Renaissance is not a new idea. ancient civilizations, culture researchers, and many others

A further parallel to the renaissance is in how the ideas were applied in new mediums and with the benefit of new technologies.  For example, sculptures from the classic antiquity were carved out of marble.  The renaissance saw a revival of the classical antiquity style in bronze.  Bronze was much stronger than marble and could be cast to produce a hollow sculpture.  This allowed stronger and lighter sculptures to be produced that captured dramatic movements.  In a similar sense, today's renaisssance draws from the ways of ancient cultures that had a sustainable lifestyle and complements that with modern technology.

Food service is thrust into the driver's seat by RF. It must straddle two complex systems, agriculture and the consumer.

=== Food service must rise to the occasion

== Homogenized food supply

The static menu has a profound influence on agricultural practices. At a very fundamental level, it can be said that the static menu is at odds with nature; It seeks a steady stream of select ingredients, something that goes against the dynamic and seasonal nature of life. 

Recall that a static menu demands access to certain fresh produce year-round. To efficiently provide this, the market seeks to grow the same item in various parts of the world. That way, the item can be freely traded and mixed in the wholesale and distribution channels. This is the essence of a commodities market.

There can be no doubt about the efficiency of the market for those items. However, this has the side-effect of making the market for other less-commodified items appear relatively less robust. Thus, farmers will choose what to grow and even what varieties to grow based on the relative strength of the underlying commodity market. This has the effect of homogenizing of food supply because specialized or niche crops will always have a weaker (and thus riskier) market.

 Another effect of commodification is that it offers farmers an (effectively) unlimited market. They have confidence in being able to sell what they produce, even if they produce a lot of it, because they can reach consumers in other regions.

== Irregularities

Another problem with highly commodified produce is the waste of irregularly shaped items. One might think that these identically-tasting discounted items would be a desirable commodity, but evidence suggests otherwise.

First, it is important to discuss the nature of the irregular items. These are perfectly edible items that don't have the typical shape of that item. This can be undesirable from several aspects. First, the ratio of edible portion may be lower (e.g. more skin to peel off). Second, the preparation may be inconvenient or incompatible. For example, it may be difficult to cut it into cubes or to get adequately thick slices. Finally, it may be aesthetically unpleasing for the consumer, particularly if it is served in whole form. Therefore, it is clear that even though they may taste the same, irregular produce __does__ have some negative aspects.

Thus, although irregularity in produce is never a desirable characteristic, exactly how bad it is is a function of the way it is prepared, with some forms of preparation not suffering in the slightest.

In such a situation, the static menu leaves no opportunity for capitalizing on the discounted produce. It cannot adapt the menu to preparations that aren't affected by the irregularity nor can it adapt the menu to feature greater portions of the discounted item. 

 RF is inherently opportunistic. It does not seek to control what and when, instead it recognizes that a suitably adaptable operation can make the best the best of whatever is available. 
 
 Again, because the market seeks a uniform supply that can be freely traded, items with irregularities are seen as breaking the uniformity of the supply and are discarded or downgraded. This is a heavy-handed approach towards dealing with a relatively minor inconvenience.
 - what is the problem with downgrading? waste is the issue


Not that it is their fault or that they are somehow more responsible, it is that they are in a strategic position from which to address.  

Food service has been thrust into limelight.

=== Rome wasn't built in a day

Having discussed RF at a very theoretical level, what it will look like in practice is a pressing matter/remains a major question. Clearly, if an establishment set out to adopt all the principles discussed here, it would look far different from anything we have seen before.  That's exciting, but would it be successful?

Thankfully, such questions never need arise in practice.  If a business owner felt such risk from making a sweeping change in their business model, then they could simply adopt the changes incrementally.  Freed from the arbitrary stigmas of a dynamic menu, business owners can explore different ingredients and dishes without committing to them.  It is fine to source from a nearby grower one day and then to use a distributor the next.  A vegetarian dish can be offered one day but not the next.  The RF consumer does not see deviations from a static menu as disorganization or mismanagement.  It is the opposite.  It is creativity, shrewd calculation at the level of the balance sheet and the recipe sheet.

In truth, the idea of a business owner perfectly gauging the tastes of their clientele is a false notion, for consumer taste itself is a moving target.  Therefore, it is wonderful that RF businesses can iterate on their menu to develop dishes that appeal more to their customer base, but the important part is not that the businesses get a second chance but that we all get a second chance.  Vegetarian dishes may not sell well in the beginning but gain traction down the road.  Nor is this a matter only of chance.  Marketing has a long and successful history of influencing consumer behavior,and there is no reason to think anything is different this time.  To the extent that RF does offer new possibilities to consumers, one must assume that it will take time for the. it is  to hit the mark.  The important part is that the mark itself can change.  

All of this is to say that the first twinklings of RF are likely to be rather anti-climatic.  And that is wonderful!  There is no real benefit for business owners to dive into uncertain waters when they could just as easily wade in slowly alongside the consumer.

A model that allows evolution and dynamism in the menu planning is eminently superior to a model with rigidity in menu planning.  

==== The hero we deserve
