= Renaissance

The Renaissance is best remembered for the stunning works of art by the likes of Rembrandt.  However the Renaissance is best understood as a shift in thinking about life, with and the treasured art just a manifestation of that new way of thinking.

Similarly, the paradigm shift of RF transcends the ingredients, the recipes and the restaurant itself and is an expression of the connection between human life and the environment. 

A second key understanding about the Renaissance is that this shift in thinking did not represent a new way of thinking. In fact, the term Renaissance means rebirth and refers to the fact that these ideas were prevalent in Greek society. Similarly the food Renaissance is not a new idea. Many, if not most, of human civilizations have related to food and their environment holistically, as a matter of necessity but also as an expression of cultural beliefs.

A final parallel to the renaissance is in how the classical ideas were applied in new mediums and with the benefit of new technologies.  For example, sculptures from the classic antiquity were carved out of marble.  The renaissance saw a revival of the classical antiquity style in bronze.  Bronze was much stronger than marble and could be cast to produce a hollow sculpture.  This allowed stronger and lighter sculptures to be produced that captured dramatic movements.  In a similar sense, RF draws from the ways of ancient cultures that had a sustainable lifestyle and complements that with modern technology.

=== Food service must rise to the occasion

Food service is thrust into the driver's seat by RF. It must straddle two complex systems, agriculture and the consumer.  Food service serves as a conduit between them.  Critically, neither side is completely knowledgable about the other.  Therefore, the role of food service is to navigate the chasm between the two.  It takes the consumers' preferences for health and sustainability and incorporates them into the menu while also accounting for agricultural and environmental constraints. 

The term conduit is an economic one. It captures the flow of resources that balance the supply and demand of the food system.  It does not, however, capture the nature of the process itself.  It suggests a sterile and impersonal transaction.  This could not be further from the truth.  In actuality, the nature of food service is nothing less than artistry.  Neither is this characterization incompatible with the earlier economic description of food service as a conduit.  

Rather, it is the economic realities of supply and demand that provide the structure and constraints in which the artistry arises. The relationship between artistry and constraints is not a new concept.  "The Japanese aesthetic tradition offers particularly deep insights into how constraints can be generative rather than limiting." <<claude-constraints-in-art>> Perhaps the best example of this is the Haiku. "The great haiku master Bashō didn't view the syllabic requirements as obstacles to overcome, but rather as a frame that helped reveal the truth he sought to capture. <<claude-constraints-in-art>>"

This enlightened perspective on the relationship between constraints and artistic expression contradicts what we might otherwise assume.  A cursory examination might conclude that limitations reduce possibilities and thus handicap the artistic process.  After all, if there were no restrictions on the number of syllables in a poem, then there would be more possible combinations of words to use in the poem.  However, the enlightened perspective shows us that this is not necessarily the case.  The constraints force the artist to focus deeply on their intent and on the essence of what they are trying to convey.  Anything unnecessary must be stripped away to ensure that the essence of their work comes through.  Purity of vision becomes paramount. 

In a culinary context, one can imagine a chef tasked with creating a healthy, affordable and convenient meal being forced to make many decisions based on these constraints. For example, there may be a very affordable, seasonal ingredient available locally, but it is something they are not very experienced with.  Without the constraints, they might use this ingredient minimally but due to the constraints they have cause to reflect more deeply on the ingredient.  How can it's qualities be accentuated?  Can it be used in new, unconventional ways?  These questions push the chef towards a deeper exploration of the ingredient and a greater appreciation of it.  In such sense, the constraints challenge the chef to rise to a richer and more profound expression of their craft.

Notably, the challenge of creating within such constraints may not always yield success. Perhaps this chef settles on a very minimal recipe, reasoning that this will maximize affordability.  Ultimately, however, consumers find the dish lacking and uninspired.

The possibility for such undesirable outcomes must be accepted to truly embrace the spirit of the RF culinary process.  For without the artistic freedom to make mistakes, there can neither be the possibility of enriching exploration.  Just as with any other art form, the culinary arts must have the latitude to explore boundaries and challenge accepted norms in a continuing evolution of preferences and values.


The dynamic nature of RF provides the perfect testbed for such exploration.  Unlike the static menu, it continually requires chefs to innovate and create in order to adapt to changing constraints.

==== RF versus gourmet cuisine

Having established that constraints can provide a framework for the creative process to flourish, it is interesting to juxtapose the creative process that RF offers with that of gourmet cuisine.

Gourmet cuisine is what most often comes to mind when people think of the culinary arts. They associate fine dining with the use of exotic ingredients and innovative recipes.  In this sense, culinary creativity is a luxury, an indulgence.

RF bucks this trend in grand fashion. It harnesses creativity to provide healthy and affordable offerings, rather than luxury ones.

At a deeper level, we might even say that the creativity necessitated by RF is more virtuous.  The constraints its struggles against are not arbitrary ones; they are constraints imposed by our biology and our environment.  To innovate within the boundaries of these constraints shows honor and respect for their significance.  Moreover, the final product carries a deep significance because it is an expression the process of seeking beauty within our natural constraints.

By contrast, the creativity in a gourmet setting is superficial.  What do the decisions made by a gourmet chef reflect?  A passing trend? A desire to surprise the diner with an exotic ingredient solely for the novelty of it? An attempt to tantalize the tastebuds as no one has ever done before? 

It is not to say that there is no challenge in these tasks. Perhaps the challenge is even greater than that of the RF chef. Nevertheless, the challenge rings hollow.  It carries little substance.  It does not honor our ecosystem and its exorbitant price point ensures that only a select few can ever enjoy it.  By contrast, the emphasis of affordability by RF is an acknowledgment of the worth of each and every human being, whereas gourmet food reinforces the economic classes that divide us.



Not only does RF buck this trend by harnessing creativity to optimize within constraints, it also offers a refreshing take on the idea of creativity in culinary arts.  

==== What is failure

Returning to the idea of allowing failure in the creative process, one must ask 

worth discussing the nature of the creative process do not hamper the creative process

If the goal is just to sell more, the pursuit becomes saccharin.  The **raison d'être** is simply profit.  It rings hollow.  It is a lost opportunity for artistry.

In gourmet cuisine, the journey from farm to table is one that must be navigated all the while swimming upstream.  robs the process of it robs food service of any 

=== Rome wasn't built in a day

Having discussed RF at a very theoretical level, what it will look like in practice is a pressing matter/remains a major question. Clearly, if an establishment set out to adopt all the principles discussed here, it would look far different from anything we have seen before.  That's exciting, but would it be successful?

Thankfully, such questions never need arise in practice.  If a business owner felt such risk from making a sweeping change in their business model, then they could simply adopt the changes incrementally.  Freed from the arbitrary stigmas of a dynamic menu, business owners can explore different ingredients and dishes without committing to them.  It is fine to source from a nearby grower one day and then to use a distributor the next.  A vegetarian dish can be offered one day but not the next.  The RF consumer does not see deviations from a static menu as disorganization or mismanagement.  It is the opposite.  It is creativity, shrewd calculation at the level of the balance sheet and the recipe sheet.

In truth, the idea of a business owner perfectly gauging the tastes of their clientele is a false notion, for consumer taste itself is a moving target.  Therefore, it is wonderful that RF businesses can iterate on their menu to develop dishes that appeal more to their customer base, but the important part is not that the businesses get a second chance but that we all get a second chance.  Vegetarian dishes may not sell well in the beginning but gain traction down the road.  Nor is this a matter only of chance.  Marketing has a long and successful history of influencing consumer behavior,and there is no reason to think anything is different this time.  To the extent that RF does offer new possibilities to consumers, one must assume that it will take time for the. it is  to hit the mark.  The important part is that the mark itself can change.  

All of this is to say that the first twinklings of RF are likely to be rather anti-climatic.  And that is wonderful!  There is no real benefit for business owners to dive into uncertain waters when they could just as easily wade in slowly alongside the consumer.

A model that allows evolution and dynamism in the menu planning is eminently superior to a model with rigidity in menu planning.  

==== The hero we deserve
