== Renaissance

The Renaissance is best remembered for the stunning works of art and sculpture and paintings by the likes of Rembrandt.  However the Renaissance is best understood as a shift in thinking about life itself, with the paintings that have been handed down to us from that time representing a manifestation of that new way of thinking.

Similarly, the food Renaissance I have been arguing for transcends the ingredients, the recipes and the restaurant itself and is an expression of the connection between human life and the environment. 

a second key understanding about the Renaissance is that this shift in thinking did not represent a new way of thinking. in fact the term Renaissance means rebirth and refers to the fact that these ideas were prevalent in Greek society. similarly the food Renaissance is not a new idea. ancient civilizations, culture researchers, and many others

A further parallel to the renaissance is in how the ideas were applied in new mediums and with the benefit of new technologies.  For example, sculptures from the classic antiquity were carved out of marble.  The renaissance saw a revival of the classical antiquity style in bronze.  Bronze was much stronger than marble and could be cast to produce a hollow sculpture.  This allowed stronger and lighter sculptures to be produced that captured dramatic movements.  In a similar sense, today's renaisssance draws from the ways of ancient cultures that had a sustainable lifestyle and complements that with modern technology.

Food service is thrust into the driver's seat by RF. It must straddle two complex systems, agriculture and the consumer.

=== Rome wasn't built in a day

Having discussed RF at a very theoretical level, what it will look like in practice is major question. Clearly, if an establishment set out to adopt all the principles discussed here, it would look far different from anything we have seen before.  That's exciting, but would it be successful?

Thankfully, such questions never need arise in practice.  If a business owner felt such risk from making a sweeping change in their business model, then they could simply adopt the changes incrementally.  Freed from the arbitrary stigmas of a dynamic menu, business owners can explore different ingredients and dishes without committing to them.  It is fine to source from a nearby grower one day and then to use a distributor the next.  A vegetarian dish can be offered one day but not the next.  The RF consumer does not see deviations from a static menu as disorganization or mismanagement.  It is the opposite.  It is creativity, shrewd calculation at the level of the balance sheet and the recipe. 

In truth, the idea of a business owner perfectly gauging the tastes of their clientele is a false notion, for consumer taste itself is a moving target.  Therefore, it is wonderful that RF businesses can iterate on their menu to develop dishes that appeal more to their customer base, but the important part is not that the businesses get a second chance but that we all get a second chance.  Vegetarian dishes may not sell well in the beginning but gain traction down the road.  Nor is this a matter only of chance.  Marketing has a long and successful history of influencing consumer behavior,and there is no reason to think anything is different this time.  To the extent that RF does offer new possibilities to consumers, one must assume that it will take time for the. it is  to hit the mark.  The important part is that the mark itself can change.  

All of this is to say that the first twinklings of RF are likely to be rather anti-climatic.  And that is wonderful!  There is no real benefit for business owners to dive into uncertain waters when they could just as easily wade in slowly.
