== Why it matters

Thus far, the discussion has been centered on the economics of a food service establishment. This was intended to show the possibilities for quick, cheap and healthy food at a fundamental level. Notably, these possibilities arise not from technical innovation or government interventions, but from the business model itself.

Having established that quick, cheap and healthy food (at least in some form) is a possibility, the bigger question becomes why that matters. After all, there are a lot of things that we could be doing better as a society, especially if we consider them as theoretically as we are now considering food service. Is food service a worthwhile cause?

The answer is a resounding "yes". There is much more at stake than what it appears. Because the impacts are so far-reaching, you may not realize how much is at stake.

=== Health impacts "Yesterday's Dinner"

The most easily foreseeable impact of the RF ideology is in healthier eating. This follows directly from the fact that the healthier food is being made cheaper and more convenient.

Healthier eating alone stands to change society significantly. The most common cause of death is from diet and lifestyle factors. Millions are invested in curbing this trend to no avail.

 __While the consequences of so-called unhealthy eating are certainly sobering,__ 

Understanding the historical progression that led us to this state helps to understand why quick, cheap and healthy food has the potential to be a game-changer.

Obesity was not always a problem. A couple generations ago, the societal impact obesity was virtually non-existent.  Few Americans were obese and cause-of-death was not tied to diet.

Importantly, this was not because everyone dined at RF-inspired food establishments.  Much to the contrary, they would have eaten significantly more home-cooked meals.

However, over time societal changes led to greater participation of women in the work-force. In turn, this left less time at home to prepare meals. Perhaps in response to this shift, the food industry began investing heavily in processed convenience foods. These foods offered a welcome respite for the weary home maker.

A second factor is that family-size has shrunk over time. This discourages cooking at home because it can be so inefficient to do in small quantities.  Recalling the lessons from the first section, we know that the marginal labor cost can decrease dramatically when cooking for larger numbers. However, smaller families often find themselves stuck on the high-end of the cost curve, devoting significant portions of time to prepare a few servings. 

Likely in response to these factors, we have observed an increasing percentage of FAFH consumption. People are increasingly choosing food service over cooking themselves. Studies like the one citing divorces due to washing dishes indicate that people view it as a chore.

In this context, RF offers a perfect antidote because it offers the convenience that people are seeking but with healthier and more affordable offerings than currently available.  What's more, it does not rely on any government involvement.

It is also perfect that RF acts via financial incentives because this means that lower socio-economic people will be more incentivized to choose RF.  (Not so) coincidentally, lower socio-economic people are disproportionately affected by obesity.  Therefore, the people who stand to benefit the most are also incentivized the most. This is a very desirable quality in any proposed solution.

 Finally, I would add that due to our relatively high standard of living our expectations for cuisine have increased to the point that many may not be willing (to devote the time) or able (to execute the recipe) to cook to their own satisfaction once becoming accustomed to FAFH.

 The average meal in the old paradigm is heavy on carbohydrates and proteins. It would greatly increase the fresh produce intake for the average person's meal.


=== Farm economics

It was noted that the volatility of produce prices discourages its use in the static menu. However, some __fresh__ produce is still used and this section will explore the implications of that.

The trouble for the static menu is two-fold: it requires the same ingredients year-round and it does not use very much of those ingredients. Under these circumstances, the static menu has almost no choice but to rely on distributors and other intermediaries.

By sourcing from growers in different geographic regions, these intermediaries can offer a consistent supply of (otherwise seasonal) ingredients.  Moreover, they serve as a single point of contact for multiple ingredients, even beyond the produce that necessitates them. This is convenient for the static menu, which offers many dishes and hence requires many ingredients.

In essence, distributors reduce the transaction costs of sourcing ingredients. And they do so to such a degree that the static menu might not be possible without them. Their facilitation underpins the entire business model.

- The establishment does not need to maintain relationships with multiple growers around the world.

Financially speaking, the price for this facilitation is enormous. A study in the UK found that apple farmers received only one percent of the retail sales price in profit <<sustain-profit>>.  This marks a new low in a worrying trend of declining farm profits that has been impacting the industry for years.

With these dwindling profits now threatening the very livelihood of the farmers - and with that, the nation's food security - some have called for regulation of the markets to ensure that farmers receive a bigger portion of the proceeds.  They argue that the power dynamics of the market leave the farmer at a disadvantage against the intermediaries they sell to. 

 Worse yet, farmers income has been trending downward for years now.  Therefore, the farmer has an increasingly urgent need to increase profitability and selling directly to food service would be just the opportunity needed.  

Within this context, RF offers something both very powerful and unforeseen: a new buyer. And not just any buyer, but one from the retail sector instead of an intermediary.  If a favorable arrangement can be made between these two parties, then the unfair dynamics of the farmer-intermediary relationship can simply be avoided rather than policed. Moreover, this new buyer could even help balance the dynamics of that relationship by empowering the farmer in negotiations.

The emergence of this new potential buyer owes directly to the RF ideology. The conventional static menu cannot fathom sourcing directly from the farmer.  However, because RF establishments are value-focused, have such a limited menu, and can adapt the menu based on the availability of ingredients, it provides a powerful vehicle for allocating large volumes of varying produce.

Seen in this light, the shortcomings of the static menu come into clearer focus.  It is adept at producing the same dish day-in and day-out, but lacks any dynamism, which makes it reliant on intermediaries to provide a consistent supply of the same ingredients. RF, on the other hand, embraces of inherent seasonality and variability of produce and seeks to capitalize on it by constantly adapting the menu to the best available ingredients.

It is important to emphasize the aspect of transaction costs for RF. RF establishments likely face significant transaction costs relative to the static menu. However, because these costs are fixed, RF seeks large purchases in which transaction costs represent a minimal portion of the total cost. Importantly, larger purchases also lend to better prices which further offset the transaction costs. __This is significant because one of the biggest impediments to farmer-sourcing for the static menu is the transaction costs.__

To be clear, obtaining ingredients from a distributor would still be infinitely more convenient. Everything from the ordering to billing will likely be much more streamlined. The point is that these conveniences become less significant the larger transaction, eventually amounting to a minor consideration.

 seasonality is only a matter of cost and not actually a question of availability. 

==== Farm labor

- Move section to permaculture
- Problem with this section...Better to argue that we need higher skilled agricultural work that favors long-term employment over seasonal work. Permaculture and diversified tasks could offer that.  
 - RF embraces the dynamic nature of agriculture and seeks to adapt to it. This means a constantly evolving set of tasks and priorities. In turn, higher skill sets are required.  Careful attention and adaptability are required. Knowledge and experience carry greater worth.

A tangential topic to farm profits is farm labor.  It is well-known that the current agricultural industry in dependent on labor from undocumented immigrants.

This is a complex issue intersecting things like immigration policy, power exploitation and farm economics.  RF cannot address all of these factors but it could significantly affect farm economics. Simply put, if the farmers themselves are facing financial struggles, it will be that much harder for them to pay higher wages and provide better working conditions.

This is not meant to excuse the situation. To the contrary, this removes a major complicating factor in achieving meaningful improvements in these issues.  To the extent that farmers face financial hardships, there will be incentive to excuse the issues because of fear of bankrupting the very people who secure the nations food supply.  With farmers on the ropes, we are hamstrung in addressing the issues that occur on those farms. Increasing farm profits will bring the other issues into clearer focus.

In _Perilous Bounty_ the author recounts an interview with a farmer in then Central Valley.  The farmer tells how his business is uncertain due to increasing labor costs.

Argument for illegal immigrants is that cannot pay a good wage and simultaneously meet the demands of the American populace. In fact, unlike all other industries, the federal law mandating additional pay for more than 40 hours per week does not apply to agriculture.  However, this has been changed by the state legislature effective 2022 and in 2023 the state's minimum wage increases.

 If the increased cost of labor translates to higher costs of fruits and vegetables then that makes it harder to provide healthy food.


include::renaissance/regenerative_agriculture.adoc[]

include::renaissance/kitchen_rehab.adoc[]

=== Short chains, long links

It's not about local it's about short chains.  But short chains are more easily formed.


=== Misc

- CSA model with farmers could offset insurance expense. Is it harder to insure a varied set of crops?

 In this sense, we see profound benefits of the new food paradigm well past the food service industry.  The agricultural industry, directly upstream of the food service industry, has the potential for many positive changes.

== Cheap, healthy food

Yet at the same time, there are marked anomalies to this pattern. Australian study found that healthy food was 17% cheaper than unhealthy. How not to diet notes that commodities such as beans have razor-thin margins and are often sold as loss-leaders.


- Not as vulnerable to short-term labor fluctuations like someone calling in sick.

include::home_economics.adoc[]

== Ready when you are - "Just-in-time" delivery and advanced logistics

=== Professionalism/education

FDR's cabinet was composed of people who had not been professionals. The new deal had a "heavy reliance upon organizer labor and its tendency to see issues through the lens of social class".

=== Diet

"I can't stress enough is becoming overweight is a normal, natural response to the abnormal, unnatural ubiquity of calorie dense, sugary, and fatty foods."

=== Policy

" *Link private sector action to incentives.*
Each incentive policy should include a private sector action paired with an incentive, or package of incentives, that reduces the cost to businesses to implement it. For example, to offer fresh produce, corner store owners may need to purchase refrigeration equipment and pay higher utility bills to run that equipment. Store owners will also need to advertise the fresh produce to customers. Local agencies could offer loans or grants to help purchase refrigeration equipment, or offer tax credits or reduced fees for business licenses. The economic development agency or public health department could provide free advertising materials, such as signs or advertisements in local media, to help promote the new healthy selections." <<6>>

== Ideas

_This is because the marginal benefits of more menu variety have greatly diminishing returns.  That is to say, a restaurant has a strong incentive to offer a baseline level of variety in their offerings. Yet on the other hand, there is very little to be gained by exceeding that threshold._

This trade-off between selection (or variety) and value is the first key dynamic to take note of.  Generally speaking, food service caters to the selection side of the spectrum, leaving the value side of the spectrum a relatively uncharted landscape.  Indeed, the entirety of what follows could be considered an exploration of this value-oriented landscape.  Within this exploration, we will highlight new features/what factors are most prominent in this new landscape as well as value itself and what our expectations should be.

One caveat is that a person only eats one meal, such that no matter how many items are on the menu, a given person will rarely ever order more than one.  

In what follows, I will expand on this idea and attempt to paint a picture of a new food service paradigm that can not only deliver on the quick, healthy and affordable meal but also on environmental, social, and economic issues to boot.  But we’re getting ahead of ourselves now, let’s back up to that imaginary restaurant with its limited menu and talk some basic economics.

== Home economics

It is not worth peoples' time to reduce waste in the kitchen, or even necessarily to eat healthy; the costs are too high and the other demands of life too great.

Americans do not even get enough sleep. No one says they don't like sleep.

== Crop choice

_Perilous Bounty_ recounts how growing an older variety of melons yields a better tasting melon, however it requires multiple passes during harvest because the melons do not all ripen at the same time.  By contrast, other growers use conventional varieties that all ripen at roughly the same time but do not taste as good.  This is just one example of a compromise due to cost constraints at the farm level.


Americans do not want to do not want to do the work because it is too hard and pays too little.  Work is too sporadic.

If work is sporadic then points to the ability of internet to bridge the gap.  If pay is too little, then trim waste downstream and increase pay upstream.

== New frontier of ethics

Unions are part of the new frontier. Would you trust a company to not cut corners and to be honest with you as a consumer if they are not honest with their employees.

== Efficiency of food service

Perhaps one of the most important questions for any restaurant is what food they are going to serve.  And for a restaurant with a limited menu that question is arguably even more relevant.

We have already noted that one of the shortcomings of the existing food service industry is that more nutritious food tends to be more expensive.  To that end, one of the first concerns ought to be efficiency, and even more specifically, the marginal cost of the menu items.

== My way or the highway

This brings us to one of the first realizations of the food industry: made-to-order menu items restrict opportunities for greater efficiency, creating a “floor” that the marginal cost cannot go below.

This concept is easier to understand with an example.  Consider a classic, made-to-order item such as a burger as compared to a prepare-ahead food such as soup.  The first apparent difference is that the made-to-order food tends to suffer in quality the longer it sits, hence why it was made-to-order in the first place.  In the case of the burger, it is a veritable train wreck of diminishing quality.  Starting with the toasted bun that arrives warm and toasty only to begin cooling and hardening.  The condiments that make that very same bun soggy the longer they sit.  The delicate lettuce that is sandwiched between the warm bun and the meat, beginning the wilting process almost on contact.  And let us not forget the accompanying side, which is almost certainly french fries and which begin to lose their crispy delicious texture as they cool.  Nearly every single aspect of the unassuming burger and fries is actually a precarious combination of ingredients that rapidly change in texture and desirability as they sit.  If that weren’t enough, it also happens that mitigating or recovering some of the desirability is near impossible.  You can't just toss it in the microwave and make it more appetizing.  

== Conclusion (Part 1)

== Part 3 - Renaissance

The benefit of RF is that an establishment does not have to perfectly embody any of the principles  hit the mark from the beginning.  

Rather than worry about perfectly designing a restaurant  the mark of
Could we perfectly hit the mark of something that we have never  and focused on the potential for benefits from RF, it is an open question athe expectations for what RF looks like in practice

== Opportunity at large

Scaling these concepts to the point that you have a relationship with the customer so you can use reusable metal packaging and have an account with them.


== Brainstorming

- Encouraging the consumer to customize ("Have it your way")

- Ordinary restaurants seek to woo you when you are craving food. "Love me and leave me".  Value-based food looks to build a relationship such that you are inclined to dine there long before hunger sets in.

- App called Food Bank, a payment provider for many restaurants. Skip credit card fees.

- App called Open Season for meeting farmers to buy produce from

There is a peculiar absence of any real scale in the freshly prepared foods category.  

[1] Perceived variety and the idea of many items derived from one base ingredient allowing many items to be made, like with pizza.
